<?php

declare(strict_types=1);
use App\Models\User;
use Modules\Distribution\Domain\Models\Distributor;

/**
 * Route authorization mapping (PROGRESS R0.9, KONSEP §A14.3).
 *
 * Maps route names (or "METHOD uri") to:
 * - "public": publicly accessible
 * - "auth": requires authenticated user
 * - ["roles" => [...], "params" => fn () => [...]]
 */
return [
    'GET /' => 'public',
    'GET up' => 'public',
    'POST confirm-password' => 'auth',
    'POST login' => 'public',
    'POST register' => 'public',
    'activity.index' => 'auth',
    'admin.audit-logs.index' => ['roles' => ['admin']],
    'admin.audit-logs.show' => ['roles' => ['admin']],
    'admin.group-dashboard' => ['roles' => ['admin']],
    'admin.health.index' => ['roles' => ['admin']],
    'admin.health.run' => ['roles' => ['admin']],
    'admin.ledger.adjust' => ['roles' => ['admin']],
    'admin.ledger.freeze' => ['roles' => ['admin']],
    'admin.ledger.index' => ['roles' => ['admin']],
    'admin.ledger.show' => ['roles' => ['admin']],
    'admin.rbac.assign' => ['roles' => ['admin']],
    'admin.rbac.index' => ['roles' => ['admin']],
    'admin.rbac.revoke' => ['roles' => ['admin']],
    'admin.rbac.role' => ['roles' => ['admin']],
    'admin.rbac.toggle-permission' => ['roles' => ['admin']],
    'admin.rbac.user' => ['roles' => ['admin']],
    'agency.accruals.clawback' => ['roles' => ['admin', 'procurement']],
    'agency.accruals.release' => ['roles' => ['admin', 'procurement']],
    'agency.accruals.store' => ['roles' => ['admin', 'procurement']],
    'agency.agents.store' => ['roles' => ['admin', 'procurement']],
    'agency.agents.transition' => ['roles' => ['admin', 'procurement']],
    'agency.attributions.store' => ['roles' => ['admin', 'procurement']],
    'agency.brands.store' => ['roles' => ['admin', 'procurement']],
    'agency.certifications.store' => ['roles' => ['admin', 'procurement']],
    'agency.compliance.store' => ['roles' => ['admin', 'procurement']],
    'agency.fraud.store' => ['roles' => ['admin', 'procurement']],
    'agency.index' => ['roles' => ['admin', 'agent', 'auditor', 'procurement']],
    'agency.leads.convert' => ['roles' => ['admin', 'procurement']],
    'agency.leads.store' => ['roles' => ['admin', 'procurement']],
    'agency.payouts.approve' => ['roles' => ['admin', 'procurement']],
    'agency.payouts.store' => ['roles' => ['admin', 'procurement']],
    'agency.schemes.store' => ['roles' => ['admin', 'procurement']],
    'agency.show' => ['roles' => ['admin', 'agent', 'auditor', 'procurement']],
    'agri.index' => 'auth',
    'api.global-search' => 'auth',
    'api.v1.logistics.quotes.store' => 'auth',
    'api.v1.logistics.shipments.index' => 'auth',
    'api.v1.logistics.shipments.show' => 'auth',
    'api.v1.logistics.shipments.store' => 'auth',
    'api.v1.logistics.tracking.show' => 'public',
    'asset.audit' => ['roles' => ['admin', 'asset_manager']],
    'asset.checkin' => ['roles' => ['admin', 'asset_manager']],
    'asset.checkout' => ['roles' => ['admin', 'asset_manager']],
    'asset.create' => ['roles' => ['admin', 'asset_manager']],
    'asset.depreciate' => ['roles' => ['admin', 'asset_manager']],
    'asset.depreciation.index' => ['roles' => ['admin', 'asset_manager']],
    'asset.depreciation.run' => ['roles' => ['admin', 'asset_manager']],
    'asset.disposal.finalize' => ['roles' => ['admin', 'asset_manager']],
    'asset.disposal.request' => ['roles' => ['admin', 'asset_manager']],
    'asset.index' => ['roles' => ['admin', 'asset_manager']],
    'asset.insurance.store' => ['roles' => ['admin', 'asset_manager']],
    'asset.leases.pay' => ['roles' => ['admin', 'asset_manager']],
    'asset.leases.store' => ['roles' => ['admin', 'asset_manager']],
    'asset.move' => ['roles' => ['admin', 'asset_manager']],
    'asset.move.approve' => ['roles' => ['admin', 'asset_manager']],
    'asset.revaluation.apply' => ['roles' => ['admin', 'asset_manager']],
    'asset.revaluation.request' => ['roles' => ['admin', 'asset_manager']],
    'asset.scan' => ['roles' => ['admin', 'asset_manager']],
    'asset.scan.form' => ['roles' => ['admin', 'asset_manager']],
    'asset.show' => ['roles' => ['admin', 'asset_manager']],
    'asset.store' => ['roles' => ['admin', 'asset_manager']],
    'asset.verify-chain' => ['roles' => ['admin', 'asset_manager']],
    'asset.work-orders.complete' => ['roles' => ['admin', 'asset_manager']],
    'asset.work-orders.store' => ['roles' => ['admin', 'asset_manager']],
    'autodex.garage.index' => 'auth',
    'autodex.garage.toggle' => 'auth',
    'autodex.index' => 'auth',
    'autodex.show' => 'auth',
    'autodex.wishlist.toggle' => 'auth',
    'b2b.index' => 'auth',
    'bookings.addSparepart' => ['roles' => ['admin', 'mekanik']],
    'bookings.approveExtra' => 'auth',
    'bookings.assign' => ['roles' => ['admin', 'mekanik']],
    'bookings.create' => 'auth',
    'bookings.invoice' => 'auth',
    'bookings.pay' => 'auth',
    'bookings.refund' => 'auth',
    'bookings.removeSparepart' => ['roles' => ['admin', 'mekanik']],
    'bookings.show' => 'auth',
    'bookings.store' => 'auth',
    'bookings.updateStatus' => ['roles' => ['admin', 'mekanik']],
    'boost.browser-logs' => 'public',
    'contract.advance.pay' => ['roles' => ['admin', 'contract_manager', 'legal']],
    'contract.amend' => ['roles' => ['admin', 'contract_manager', 'legal']],
    'contract.append-version' => ['roles' => ['admin', 'contract_manager', 'legal']],
    'contract.attachment.destroy' => ['roles' => ['admin', 'contract_manager', 'legal']],
    'contract.attachment.store' => ['roles' => ['admin', 'contract_manager', 'legal']],
    'contract.clauses.create' => ['roles' => ['admin', 'contract_manager', 'legal']],
    'contract.clauses.edit' => ['roles' => ['admin', 'contract_manager', 'legal']],
    'contract.clauses.index' => ['roles' => ['admin', 'contract_manager', 'legal']],
    'contract.clauses.store' => ['roles' => ['admin', 'contract_manager', 'legal']],
    'contract.clauses.update' => ['roles' => ['admin', 'contract_manager', 'legal']],
    'contract.create' => ['roles' => ['admin', 'contract_manager', 'legal']],
    'contract.edit' => ['roles' => ['admin', 'contract_manager', 'legal']],
    'contract.escalation.apply' => ['roles' => ['admin', 'contract_manager', 'legal']],
    'contract.escalation.preview' => ['roles' => ['admin', 'contract_manager', 'legal']],
    'contract.index' => ['roles' => ['admin', 'contract_manager', 'legal']],
    'contract.milestone.complete' => ['roles' => ['admin', 'contract_manager', 'legal']],
    'contract.milestone.store' => ['roles' => ['admin', 'contract_manager', 'legal']],
    'contract.obligations' => ['roles' => ['admin', 'contract_manager', 'legal']],
    'contract.party.add' => ['roles' => ['admin', 'contract_manager', 'legal']],
    'contract.party.remove' => ['roles' => ['admin', 'contract_manager', 'legal']],
    'contract.reports' => ['roles' => ['admin', 'contract_manager', 'legal']],
    'contract.risk.rescore' => ['roles' => ['admin', 'contract_manager', 'legal']],
    'contract.schedule.build' => ['roles' => ['admin', 'contract_manager', 'legal']],
    'contract.schedule.pay' => ['roles' => ['admin', 'contract_manager', 'legal']],
    'contract.schedule.penalty.pay' => ['roles' => ['admin', 'contract_manager', 'legal']],
    'contract.schedule.penalty.show' => ['roles' => ['admin', 'contract_manager', 'legal']],
    'contract.schedule.penalty.waiver' => ['roles' => ['admin', 'contract_manager', 'legal']],
    'contract.schedule.penalty.waiver.apply' => ['roles' => ['admin', 'contract_manager', 'legal']],
    'contract.show' => ['roles' => ['admin', 'contract_manager', 'legal']],
    'contract.sign-party' => ['roles' => ['admin', 'contract_manager', 'legal']],
    'contract.store' => ['roles' => ['admin', 'contract_manager', 'legal']],
    'contract.submit-approval' => ['roles' => ['admin', 'contract_manager', 'legal']],
    'contract.templates.create' => ['roles' => ['admin', 'contract_manager', 'legal']],
    'contract.templates.index' => ['roles' => ['admin', 'contract_manager', 'legal']],
    'contract.templates.store' => ['roles' => ['admin', 'contract_manager', 'legal']],
    'contract.transition' => ['roles' => ['admin', 'contract_manager', 'legal']],
    'contract.update' => ['roles' => ['admin', 'contract_manager', 'legal']],
    'contract.usage.sync' => ['roles' => ['admin', 'contract_manager', 'legal']],
    'contract.version-diff' => ['roles' => ['admin', 'contract_manager', 'legal']],
    'contract.versions' => ['roles' => ['admin', 'contract_manager', 'legal']],
    'control_tower.index' => 'auth',
    'control_tower.promises' => 'auth',
    'crypto.alerts.destroy' => 'auth',
    'crypto.alerts.index' => 'auth',
    'crypto.alerts.store' => 'auth',
    'crypto.api.chart' => 'public',
    'crypto.api.prices' => 'public',
    'crypto.market.index' => 'public',
    'crypto.market.show' => 'public',
    'crypto.portfolio.index' => 'auth',
    'crypto.trade.execute' => 'auth',
    'crypto.trade.quote' => 'auth',
    'dashboard' => 'auth',
    'distribution.coverages.store' => ['roles' => ['admin', 'procurement']],
    'distribution.distributors.store' => ['roles' => ['admin', 'procurement']],
    'distribution.index' => ['roles' => ['admin', 'auditor', 'distributor', 'procurement']],
    'distribution.invoices.pay' => ['roles' => ['admin', 'procurement']],
    'distribution.invoices.store' => ['roles' => ['admin', 'procurement']],
    'distribution.onboarding.approve' => ['roles' => ['admin', 'procurement']],
    'distribution.onboarding.submit' => ['roles' => ['admin', 'procurement']],
    'distribution.outlets.store' => ['roles' => ['admin', 'procurement']],
    'distribution.portal.home' => [
        'roles' => ['admin', 'distributor'],
        'setup' => function (User $user): void {
            if (class_exists(Distributor::class)) {
                Distributor::firstOrCreate(
                    ['owner_user_id' => $user->id],
                    ['name' => 'Dist Test', 'code' => 'DST-'.$user->id, 'tier' => 'bronze', 'is_active' => true]
                );
            }
        },
    ],
    'distribution.scorecards.store' => ['roles' => ['admin', 'procurement']],
    'distribution.securities.store' => ['roles' => ['admin', 'procurement']],
    'distribution.show' => ['roles' => ['admin', 'auditor', 'distributor', 'procurement']],
    'distribution.sweep' => ['roles' => ['admin', 'procurement']],
    'distribution.targets.store' => ['roles' => ['admin', 'procurement']],
    'distribution.territories.store' => ['roles' => ['admin', 'procurement']],
    'distribution.tier.evaluate' => ['roles' => ['admin', 'procurement']],
    'distribution.transition' => ['roles' => ['admin', 'procurement']],
    'enterprise_finance.budgets' => 'auth',
    'enterprise_finance.index' => 'auth',
    'epc.index' => 'auth',
    'esg.index' => 'auth',
    'estimates.approve' => 'auth',
    'estimates.receiveBackorder' => ['roles' => ['admin', 'mekanik']],
    'estimates.reject' => 'auth',
    'estimates.send' => ['roles' => ['admin', 'mekanik']],
    'estimates.store' => ['roles' => ['admin', 'mekanik']],
    'finance.loans.index' => 'auth',
    'finance.loans.payInstallment' => 'auth',
    'finance.loans.payOff' => 'auth',
    'finance.loans.quote' => 'auth',
    'finance.loans.show' => 'auth',
    'finance.loans.simulate' => 'auth',
    'finance.loans.store' => 'auth',
    'finance.loans.topUpCollateral' => 'auth',
    'hcm.index' => 'auth',
    'integration.index' => 'auth',
    'integration.webhooks' => 'auth',
    'intercompany.index' => 'auth',
    'intercompany.transactions' => 'auth',
    'international.index' => 'auth',
    'international.jvs' => 'auth',
    'login' => 'public',
    'logistics.carriers.index' => 'auth',
    'logistics.carriers.pay' => 'auth',
    'logistics.carriers.store' => 'auth',
    'logistics.claims.decide' => 'auth',
    'logistics.claims.index' => 'auth',
    'logistics.claims.pay' => 'auth',
    'logistics.claims.store' => 'auth',
    'logistics.claims.submit' => 'auth',
    'logistics.cod.deposit' => 'auth',
    'logistics.cod.index' => 'auth',
    'logistics.control-tower.index' => 'auth',
    'logistics.customs.clear' => 'auth',
    'logistics.customs.index' => 'auth',
    'logistics.customs.pay' => 'auth',
    'logistics.customs.store' => 'auth',
    'logistics.customs.tariffs.store' => 'auth',
    'logistics.dashboard' => 'auth',
    'logistics.dd.end' => 'auth',
    'logistics.dd.index' => 'auth',
    'logistics.dd.invoice' => 'auth',
    'logistics.dd.start' => 'auth',
    'logistics.dd.tariffs.store' => 'auth',
    'logistics.dispatch.assign' => 'auth',
    'logistics.dispatch.assign-shipment' => 'auth',
    'logistics.dispatch.index' => 'auth',
    'logistics.dispatch.release' => 'auth',
    'logistics.driver.deliver' => 'auth',
    'logistics.driver.fail' => 'auth',
    'logistics.driver.pickup' => 'auth',
    'logistics.driver.start-delivery' => 'auth',
    'logistics.driver.tasks' => 'auth',
    'logistics.drivers.index' => 'auth',
    'logistics.exceptions.index' => 'auth',
    'logistics.exceptions.resolve' => 'auth',
    'logistics.exceptions.store' => 'auth',
    'logistics.fleet.index' => 'auth',
    'logistics.fuel.index' => 'auth',
    'logistics.fuel.store' => 'auth',
    'logistics.hub.inbound' => 'auth',
    'logistics.hub.index' => 'auth',
    'logistics.hub.outbound' => 'auth',
    'logistics.hub.sort' => 'auth',
    'logistics.lanes.destroy' => 'auth',
    'logistics.lanes.index' => 'auth',
    'logistics.lanes.store' => 'auth',
    'logistics.legs.assign-carrier' => 'auth',
    'logistics.legs.complete' => 'auth',
    'logistics.locations.create' => 'auth',
    'logistics.locations.destroy' => 'auth',
    'logistics.locations.edit' => 'auth',
    'logistics.locations.index' => 'auth',
    'logistics.locations.store' => 'auth',
    'logistics.locations.update' => 'auth',
    'logistics.margins' => 'auth',
    'logistics.shipments.bulk' => 'auth',
    'logistics.shipments.bulk.process' => 'auth',
    'logistics.shipments.create' => 'auth',
    'logistics.shipments.errors' => 'auth',
    'logistics.shipments.index' => 'auth',
    'logistics.shipments.label' => 'auth',
    'logistics.shipments.show' => 'auth',
    'logistics.shipments.store' => 'auth',
    'logistics.shipments.template' => 'auth',
    'logout' => 'auth',
    'mall.billing.apply-penalties' => 'auth',
    'mall.billing.generate' => 'auth',
    'mall.billing.index' => 'auth',
    'mall.directory.index' => 'public',
    'mall.events.index' => 'auth',
    'mall.events.store' => 'auth',
    'mall.facilities.bill-tenant' => 'auth',
    'mall.facilities.generate-pm' => 'auth',
    'mall.facilities.index' => 'auth',
    'mall.invoices.auto-debit' => 'auth',
    'mall.invoices.show' => 'auth',
    'mall.leases.activate' => 'auth',
    'mall.leases.create' => 'auth',
    'mall.leases.index' => 'auth',
    'mall.leases.renew' => 'auth',
    'mall.leases.show' => 'auth',
    'mall.leases.store' => 'auth',
    'mall.leases.terminate' => 'auth',
    'mall.loyalty.claim' => 'auth',
    'mall.loyalty.index' => 'auth',
    'mall.loyalty.redeem' => 'auth',
    'mall.loyalty.settle' => 'auth',
    'mall.loyalty.use' => 'auth',
    'mall.parking.footfall' => 'auth',
    'mall.parking.gate.check-in' => 'auth',
    'mall.parking.gate.check-out' => 'auth',
    'mall.parking.gate.entry' => 'auth',
    'mall.parking.gate.exit' => 'auth',
    'mall.parking.gate.lost-ticket' => 'auth',
    'mall.parking.gate.settle' => 'auth',
    'mall.parking.index' => 'auth',
    'mall.parking.members' => 'auth',
    'mall.parking.members.store' => 'auth',
    'mall.parking.occupancy' => 'auth',
    'mall.parking.validate' => 'auth',
    'mall.portal.index' => 'auth',
    'mall.portal.invoice' => 'auth',
    'mall.portal.overtime' => 'auth',
    'mall.portal.pay' => 'auth',
    'mall.portal.sales' => 'auth',
    'mall.portal.sales.store' => 'auth',
    'mall.site-plan.index' => 'auth',
    'mall.tenants.create' => 'auth',
    'mall.tenants.index' => 'auth',
    'mall.tenants.show' => 'auth',
    'mall.tenants.store' => 'auth',
    'mall.utilities.batch' => 'auth',
    'mall.utilities.index' => 'auth',
    'manufacturing.boms.store' => ['roles' => ['admin', 'planner']],
    'manufacturing.costing.index' => ['roles' => ['admin', 'auditor', 'planner']],
    'manufacturing.costing.versions.approve' => ['roles' => ['admin', 'auditor', 'planner']],
    'manufacturing.costing.versions.submit' => ['roles' => ['admin', 'auditor', 'planner']],
    'manufacturing.formulas.approve' => ['roles' => ['admin', 'qc_inspector']],
    'manufacturing.formulas.store' => ['roles' => ['admin', 'planner']],
    'manufacturing.formulas.submit' => ['roles' => ['admin', 'planner']],
    'manufacturing.index' => ['roles' => ['admin', 'operator', 'planner', 'qc_inspector']],
    'manufacturing.maintenance.incidents.close' => ['roles' => ['admin', 'asset_manager', 'auditor', 'operator', 'planner']],
    'manufacturing.maintenance.incidents.store' => ['roles' => ['admin', 'asset_manager', 'auditor', 'operator', 'planner']],
    'manufacturing.maintenance.index' => ['roles' => ['admin', 'asset_manager', 'auditor', 'operator', 'planner']],
    'manufacturing.maintenance.oee.compute' => ['roles' => ['admin', 'asset_manager', 'auditor', 'operator', 'planner']],
    'manufacturing.maintenance.orders.store' => ['roles' => ['admin', 'asset_manager', 'auditor', 'operator', 'planner']],
    'manufacturing.maintenance.orders.transition' => ['roles' => ['admin', 'asset_manager', 'auditor', 'operator', 'planner']],
    'manufacturing.maintenance.parts.store' => ['roles' => ['admin', 'asset_manager', 'auditor', 'operator', 'planner']],
    'manufacturing.maintenance.permits.approve' => ['roles' => ['admin', 'asset_manager', 'auditor', 'operator', 'planner']],
    'manufacturing.maintenance.permits.store' => ['roles' => ['admin', 'asset_manager', 'auditor', 'operator', 'planner']],
    'manufacturing.maintenance.sensors.store' => ['roles' => ['admin', 'asset_manager', 'auditor', 'operator', 'planner']],
    'manufacturing.materials.store' => ['roles' => ['admin', 'planner']],
    'manufacturing.planning.balances.store' => ['roles' => ['admin', 'planner']],
    'manufacturing.planning.forecast.activate' => ['roles' => ['admin', 'planner']],
    'manufacturing.planning.forecast.store' => ['roles' => ['admin', 'planner']],
    'manufacturing.planning.index' => ['roles' => ['admin', 'planner']],
    'manufacturing.planning.mps.store' => ['roles' => ['admin', 'planner']],
    'manufacturing.planning.mrp.run' => ['roles' => ['admin', 'planner']],
    'manufacturing.planning.orders.firm' => ['roles' => ['admin', 'planner']],
    'manufacturing.planning.params.store' => ['roles' => ['admin', 'planner']],
    'manufacturing.planning.receipts.store' => ['roles' => ['admin', 'planner']],
    'manufacturing.planning.runs.propose' => ['roles' => ['admin', 'planner']],
    'manufacturing.plants.store' => ['roles' => ['admin', 'planner']],
    'manufacturing.production.downtimes.end' => ['roles' => ['admin', 'operator', 'planner', 'qc_inspector']],
    'manufacturing.production.downtimes.store' => ['roles' => ['admin', 'operator', 'planner', 'qc_inspector']],
    'manufacturing.production.index' => ['roles' => ['admin', 'operator', 'planner', 'qc_inspector']],
    'manufacturing.production.operations.finish' => ['roles' => ['admin', 'operator', 'planner', 'qc_inspector']],
    'manufacturing.production.operations.start' => ['roles' => ['admin', 'operator', 'planner', 'qc_inspector']],
    'manufacturing.production.orders.invariants' => ['roles' => ['admin', 'operator', 'planner', 'qc_inspector']],
    'manufacturing.production.orders.issue' => ['roles' => ['admin', 'operator', 'planner', 'qc_inspector']],
    'manufacturing.production.orders.receive-fg' => ['roles' => ['admin', 'operator', 'planner', 'qc_inspector']],
    'manufacturing.production.orders.scrap' => ['roles' => ['admin', 'operator', 'planner', 'qc_inspector']],
    'manufacturing.production.orders.store' => ['roles' => ['admin', 'planner']],
    'manufacturing.production.orders.transition' => ['roles' => ['admin', 'operator', 'planner', 'qc_inspector']],
    'manufacturing.quality.capas.complete' => ['roles' => ['admin', 'auditor', 'planner', 'qc_inspector']],
    'manufacturing.quality.capas.store' => ['roles' => ['admin', 'auditor', 'planner', 'qc_inspector']],
    'manufacturing.quality.index' => ['roles' => ['admin', 'auditor', 'planner', 'qc_inspector']],
    'manufacturing.quality.inspections.approve' => ['roles' => ['admin', 'auditor', 'planner', 'qc_inspector']],
    'manufacturing.quality.inspections.store' => ['roles' => ['admin', 'auditor', 'planner', 'qc_inspector']],
    'manufacturing.quality.inspections.waiver' => ['roles' => ['admin', 'auditor', 'planner', 'qc_inspector']],
    'manufacturing.quality.lots.certificates' => ['roles' => ['admin', 'auditor', 'planner', 'qc_inspector']],
    'manufacturing.quality.lots.recall' => ['roles' => ['admin', 'auditor', 'planner', 'qc_inspector']],
    'manufacturing.quality.lots.release' => ['roles' => ['admin', 'auditor', 'planner', 'qc_inspector']],
    'manufacturing.quality.lots.trace' => ['roles' => ['admin', 'auditor', 'planner', 'qc_inspector']],
    'manufacturing.quality.ncrs.store' => ['roles' => ['admin', 'auditor', 'planner', 'qc_inspector']],
    'manufacturing.quality.plans.store' => ['roles' => ['admin', 'auditor', 'planner', 'qc_inspector']],
    'manufacturing.quality.recalls.complete' => ['roles' => ['admin', 'auditor', 'planner', 'qc_inspector']],
    'manufacturing.quality.recalls.notify' => ['roles' => ['admin', 'auditor', 'planner', 'qc_inspector']],
    'manufacturing.routings.store' => ['roles' => ['admin', 'planner']],
    'manufacturing.workers.store' => ['roles' => ['admin', 'planner']],
    'notifications.index' => 'auth',
    'notifications.markAllRead' => 'auth',
    'notifications.markAllReadJson' => 'auth',
    'notifications.read' => 'auth',
    'notifications.recent' => 'auth',
    'partners.index' => ['roles' => ['admin', 'auditor', 'procurement']],
    'partners.show' => ['roles' => ['admin', 'auditor', 'procurement']],
    'partners.store' => ['roles' => ['admin', 'auditor', 'procurement']],
    'partners.transition' => ['roles' => ['admin', 'auditor', 'procurement']],
    'party.create' => ['roles' => ['admin', 'logistics_admin', 'party_manager']],
    'party.index' => ['roles' => ['admin', 'logistics_admin', 'party_manager']],
    'party.kyc.approve' => ['roles' => ['admin', 'logistics_admin', 'party_manager']],
    'party.kyc.reject' => ['roles' => ['admin', 'logistics_admin', 'party_manager']],
    'party.kyc.submit' => ['roles' => ['admin', 'logistics_admin', 'party_manager']],
    'party.legal-entities' => ['roles' => ['admin', 'logistics_admin', 'party_manager']],
    'party.legal-entities.store' => ['roles' => ['admin', 'logistics_admin', 'party_manager']],
    'party.rescore' => ['roles' => ['admin', 'logistics_admin', 'party_manager']],
    'party.screen' => ['roles' => ['admin', 'logistics_admin', 'party_manager']],
    'party.show' => ['roles' => ['admin', 'logistics_admin', 'party_manager']],
    'party.store' => ['roles' => ['admin', 'logistics_admin', 'party_manager']],
    'passport.show' => 'public',
    'password.confirm' => 'auth',
    'password.email' => 'public',
    'password.request' => 'public',
    'password.reset' => 'public',
    'password.store' => 'public',
    'password.update' => 'auth',
    'plm.index' => 'auth',
    'pricing.analytics.compute' => ['roles' => ['admin', 'auditor', 'procurement']],
    'pricing.claims.settle' => ['roles' => ['admin', 'auditor', 'procurement']],
    'pricing.claims.validate' => ['roles' => ['admin', 'auditor', 'procurement']],
    'pricing.discounts.store' => ['roles' => ['admin', 'auditor', 'procurement']],
    'pricing.index' => ['roles' => ['admin', 'auditor', 'procurement']],
    'pricing.margin-policies.store' => ['roles' => ['admin', 'auditor', 'procurement']],
    'pricing.overrides.decide' => ['roles' => ['admin', 'auditor', 'procurement']],
    'pricing.overrides.store' => ['roles' => ['admin', 'auditor', 'procurement']],
    'pricing.price-lists.activate' => ['roles' => ['admin', 'auditor', 'procurement']],
    'pricing.price-lists.items.store' => ['roles' => ['admin', 'auditor', 'procurement']],
    'pricing.price-lists.store' => ['roles' => ['admin', 'auditor', 'procurement']],
    'pricing.promotions.claims.store' => ['roles' => ['admin', 'auditor', 'procurement']],
    'pricing.promotions.store' => ['roles' => ['admin', 'auditor', 'procurement']],
    'procurement.dashboard' => ['roles' => ['admin', 'procurement']],
    'procurement.pos.cancel' => ['roles' => ['admin', 'procurement']],
    'procurement.pos.close' => ['roles' => ['admin', 'procurement']],
    'procurement.pos.import-profile' => ['roles' => ['admin', 'procurement']],
    'procurement.pos.inbound' => ['roles' => ['admin', 'procurement']],
    'procurement.pos.revise' => ['roles' => ['admin', 'procurement']],
    'procurement.pos.show' => ['roles' => ['admin', 'procurement', 'supplier']],
    'procurement.pos.store' => ['roles' => ['admin', 'procurement']],
    'procurement.quotes.store' => ['roles' => ['admin', 'procurement', 'supplier']],
    'procurement.requisitions.approve' => ['roles' => ['admin', 'procurement']],
    'procurement.requisitions.show' => ['roles' => ['admin', 'procurement', 'supplier']],
    'procurement.requisitions.store' => ['roles' => ['admin', 'procurement']],
    'procurement.rfqs.award' => ['roles' => ['admin', 'procurement']],
    'procurement.rfqs.show' => ['roles' => ['admin', 'procurement', 'supplier']],
    'procurement.rfqs.store' => ['roles' => ['admin', 'procurement']],
    'procurement.tenders.award' => ['roles' => ['admin', 'procurement']],
    'procurement.tenders.evaluate' => ['roles' => ['admin', 'procurement']],
    'procurement.tenders.open' => ['roles' => ['admin', 'procurement']],
    'procurement.tenders.seal' => ['roles' => ['admin', 'procurement', 'supplier']],
    'procurement.tenders.show' => ['roles' => ['admin', 'procurement', 'supplier']],
    'procurement.tenders.store' => ['roles' => ['admin', 'procurement']],
    'profile.api-tokens.destroy' => 'auth',
    'profile.api-tokens.store' => 'auth',
    'profile.destroy' => 'auth',
    'profile.edit' => 'auth',
    'profile.update' => 'auth',
    'register' => 'public',
    'resto.analytics.index' => 'auth',
    'resto.catering.cancel' => 'auth',
    'resto.catering.complete' => 'auth',
    'resto.catering.create' => 'auth',
    'resto.catering.deposit' => 'auth',
    'resto.catering.destroy' => 'auth',
    'resto.catering.edit' => 'auth',
    'resto.catering.index' => 'auth',
    'resto.catering.show' => 'auth',
    'resto.catering.store' => 'auth',
    'resto.catering.update' => 'auth',
    'resto.deliveries.create' => 'auth',
    'resto.deliveries.destroy' => 'auth',
    'resto.deliveries.edit' => 'auth',
    'resto.deliveries.fail' => 'auth',
    'resto.deliveries.index' => 'auth',
    'resto.deliveries.show' => 'auth',
    'resto.deliveries.status' => 'auth',
    'resto.deliveries.store' => 'auth',
    'resto.deliveries.update' => 'auth',
    'resto.franchise.contract.store' => 'auth',
    'resto.franchise.index' => 'auth',
    'resto.franchise.royalty.run' => 'auth',
    'resto.ingredients.conversions.store' => 'auth',
    'resto.ingredients.create' => 'auth',
    'resto.ingredients.destroy' => 'auth',
    'resto.ingredients.edit' => 'auth',
    'resto.ingredients.index' => 'auth',
    'resto.ingredients.show' => 'auth',
    'resto.ingredients.store' => 'auth',
    'resto.ingredients.update' => 'auth',
    'resto.kitchen.cook' => 'auth',
    'resto.kitchen.index' => 'auth',
    'resto.kitchen.simulate' => 'auth',
    'resto.kitchen.trays.discard' => 'auth',
    'resto.kitchen.trays.recirculate' => 'auth',
    'resto.menu.calculate-cost' => 'auth',
    'resto.menu.create' => 'auth',
    'resto.menu.destroy' => 'auth',
    'resto.menu.edit' => 'auth',
    'resto.menu.index' => 'auth',
    'resto.menu.show' => 'auth',
    'resto.menu.store' => 'auth',
    'resto.menu.update' => 'auth',
    'resto.outlets.create' => 'auth',
    'resto.outlets.destroy' => 'auth',
    'resto.outlets.edit' => 'auth',
    'resto.outlets.index' => 'auth',
    'resto.outlets.show' => 'auth',
    'resto.outlets.store' => 'auth',
    'resto.outlets.update' => 'auth',
    'resto.pos.index' => 'auth',
    'resto.pos.order.pay' => 'auth',
    'resto.pos.order.receipt' => 'auth',
    'resto.pos.order.validate-parking' => 'auth',
    'resto.pos.order.void' => 'auth',
    'resto.pos.session.bill' => 'auth',
    'resto.pos.session.hidang' => 'auth',
    'resto.pos.session.item' => 'auth',
    'resto.pos.session.open' => 'auth',
    'resto.pos.session.show' => 'auth',
    'resto.pos.shift.close' => 'auth',
    'resto.pos.shift.open' => 'auth',
    'resto.pos.shift.settle' => 'auth',
    'resto.purchases.create' => 'auth',
    'resto.purchases.destroy' => 'auth',
    'resto.purchases.edit' => 'auth',
    'resto.purchases.index' => 'auth',
    'resto.purchases.pay' => 'auth',
    'resto.purchases.receive' => 'auth',
    'resto.purchases.show' => 'auth',
    'resto.purchases.store' => 'auth',
    'resto.purchases.update' => 'auth',
    'resto.stock-counts.approve' => 'auth',
    'resto.stock-counts.create' => 'auth',
    'resto.stock-counts.destroy' => 'auth',
    'resto.stock-counts.edit' => 'auth',
    'resto.stock-counts.index' => 'auth',
    'resto.stock-counts.show' => 'auth',
    'resto.stock-counts.store' => 'auth',
    'resto.stock-counts.update' => 'auth',
    'resto.transfers.create' => 'auth',
    'resto.transfers.destroy' => 'auth',
    'resto.transfers.edit' => 'auth',
    'resto.transfers.index' => 'auth',
    'resto.transfers.receive' => 'auth',
    'resto.transfers.show' => 'auth',
    'resto.transfers.store' => 'auth',
    'resto.transfers.update' => 'auth',
    'sanctum.csrf-cookie' => 'public',
    'services.destroy' => ['roles' => ['admin']],
    'services.index' => ['roles' => ['admin']],
    'services.store' => ['roles' => ['admin']],
    'services.update' => ['roles' => ['admin']],
    'spareparts.destroy' => ['roles' => ['admin']],
    'spareparts.index' => ['roles' => ['admin']],
    'spareparts.store' => ['roles' => ['admin']],
    'spareparts.update' => ['roles' => ['admin']],
    'storage.local' => 'public',
    'storage.local.upload' => 'public',
    'store.admin.orders.cancel' => ['roles' => ['admin']],
    'store.admin.orders.complete' => ['roles' => ['admin']],
    'store.admin.orders.index' => ['roles' => ['admin']],
    'store.admin.orders.resolveDispute' => ['roles' => ['admin']],
    'store.admin.orders.ship' => ['roles' => ['admin']],
    'store.admin.orders.show' => ['roles' => ['admin']],
    'store.admin.products.adjustStock' => ['roles' => ['admin']],
    'store.admin.products.createCarListing' => ['roles' => ['admin']],
    'store.admin.products.index' => ['roles' => ['admin']],
    'store.admin.products.toggle' => ['roles' => ['admin']],
    'store.c2c.buy' => 'auth',
    'store.c2c.buyForm' => 'auth',
    'store.c2c.cancel' => 'auth',
    'store.c2c.confirm' => 'auth',
    'store.c2c.dispute' => 'auth',
    'store.c2c.handover' => 'auth',
    'store.c2c.index' => 'public',
    'store.c2c.mySales' => 'auth',
    'store.c2c.store' => 'auth',
    'store.c2c.unlist' => 'auth',
    'store.cart.count' => 'auth',
    'store.cart.destroy' => 'auth',
    'store.cart.index' => 'auth',
    'store.cart.store' => 'auth',
    'store.cart.update' => 'auth',
    'store.catalog.index' => 'public',
    'store.checkout.index' => 'auth',
    'store.checkout.process' => 'auth',
    'store.orders.cancel' => 'auth',
    'store.orders.confirm' => 'auth',
    'store.orders.index' => 'auth',
    'store.orders.show' => 'auth',
    'store.products.show' => 'public',
    'supplier.certifications.store' => ['roles' => ['admin', 'party_manager', 'procurement']],
    'supplier.create' => ['roles' => ['admin', 'party_manager', 'procurement']],
    'supplier.index' => ['roles' => ['admin', 'party_manager', 'procurement']],
    'supplier.items.store' => ['roles' => ['admin', 'party_manager', 'procurement']],
    'supplier.portal.asn.ship' => [
        'roles' => ['admin', 'supplier'],
        'setup' => function (User $user): void {
            if (class_exists(\Modules\Supplier\Domain\Models\Supplier::class)) {
                \Modules\Supplier\Domain\Models\Supplier::firstOrCreate(
                    ['owner_user_id' => $user->id],
                    ['name' => 'Supplier Test', 'code' => 'SUP-'.$user->id, 'kind' => 'supplier', 'is_active' => true]
                );
            }
        },
    ],
    'supplier.portal.asn.store' => [
        'roles' => ['admin', 'supplier'],
        'setup' => function (User $user): void {
            if (class_exists(\Modules\Supplier\Domain\Models\Supplier::class)) {
                \Modules\Supplier\Domain\Models\Supplier::firstOrCreate(
                    ['owner_user_id' => $user->id],
                    ['name' => 'Supplier Test', 'code' => 'SUP-'.$user->id, 'kind' => 'supplier', 'is_active' => true]
                );
            }
        },
    ],
    'supplier.portal.documents.store' => [
        'roles' => ['admin', 'supplier'],
        'setup' => function (User $user): void {
            if (class_exists(\Modules\Supplier\Domain\Models\Supplier::class)) {
                \Modules\Supplier\Domain\Models\Supplier::firstOrCreate(
                    ['owner_user_id' => $user->id],
                    ['name' => 'Supplier Test', 'code' => 'SUP-'.$user->id, 'kind' => 'supplier', 'is_active' => true]
                );
            }
        },
    ],
    'supplier.portal.home' => [
        'roles' => ['admin', 'supplier'],
        'setup' => function (User $user): void {
            if (class_exists(\Modules\Supplier\Domain\Models\Supplier::class)) {
                \Modules\Supplier\Domain\Models\Supplier::firstOrCreate(
                    ['owner_user_id' => $user->id],
                    ['name' => 'Supplier Test', 'code' => 'SUP-'.$user->id, 'kind' => 'supplier', 'is_active' => true]
                );
            }
        },
    ],
    'supplier.qualifications.approve' => ['roles' => ['admin', 'party_manager', 'procurement']],
    'supplier.qualifications.store' => ['roles' => ['admin', 'party_manager', 'procurement']],
    'supplier.scan-risks' => ['roles' => ['admin', 'party_manager', 'procurement']],
    'supplier.scorecards.store' => ['roles' => ['admin', 'party_manager', 'procurement']],
    'supplier.show' => ['roles' => ['admin', 'party_manager', 'procurement']],
    'supplier.store' => ['roles' => ['admin', 'party_manager', 'procurement']],
    'supplier.transition' => ['roles' => ['admin', 'party_manager', 'procurement']],
    'track.index' => 'public',
    'track.show' => 'public',
    'trade.index' => 'auth',
    'trade_finance.index' => 'auth',
    'trade_finance.lcs' => 'auth',
    'treasury.index' => 'auth',
    'verification.notice' => 'auth',
    'verification.send' => 'auth',
    'verification.verify' => 'auth',
    'wallet.index' => 'auth',
    'wallet.mutasi' => 'auth',
    'wallet.mutasi.export' => 'auth',
    'wallet.pin.store' => 'auth',
    'wallet.topup.store' => 'auth',
    'wallet.transfer' => 'auth',
    'wallet.transfer.lookup' => 'auth',
    'wallet.transfer.store' => 'auth',
    'wms.cycle-counts.apply' => ['roles' => ['admin']],
    'wms.cycle-counts.store' => ['roles' => ['admin', 'hub_operator']],
    'wms.cycle-counts.submit' => ['roles' => ['admin', 'hub_operator']],
    'wms.dock.store' => ['roles' => ['admin', 'hub_operator']],
    'wms.index' => ['roles' => ['admin', 'auditor', 'hub_operator', 'procurement']],
    'wms.pick' => ['roles' => ['admin', 'hub_operator']],
    'wms.putaway' => ['roles' => ['admin', 'hub_operator']],
    'wms.replenishments.compute' => ['roles' => ['admin', 'hub_operator']],
    'wms.transfers.receive' => ['roles' => ['admin', 'hub_operator']],
    'wms.transfers.ship' => ['roles' => ['admin', 'hub_operator']],
    'wms.transfers.store' => ['roles' => ['admin', 'hub_operator']],
    'wms.warehouses.store' => ['roles' => ['admin', 'hub_operator']],
    'wms.waves.release' => ['roles' => ['admin', 'hub_operator']],
    'wms.waves.store' => ['roles' => ['admin', 'hub_operator']],
];
