<?php

declare(strict_types=1);

namespace Modules\Integration;

use Illuminate\Support\ServiceProvider;
use Modules\Integration\Application\Services\AcademicIndustryResearchService;
use Modules\Integration\Application\Services\AdvancedAnalyticsGraphResearchService;
use Modules\Integration\Application\Services\AdvancedSupplyOptimizationService;
use Modules\Integration\Application\Services\AgentHitlOrchestrationService;
use Modules\Integration\Application\Services\AgentMarketplaceGovernedToolsService;
use Modules\Integration\Application\Services\AgentSafetyGuardrailsService;
use Modules\Integration\Application\Services\AiCostSustainabilityService;
use Modules\Integration\Application\Services\AiDecisionAuditService;
use Modules\Integration\Application\Services\AiForecastingSopService;
use Modules\Integration\Application\Services\AiFraudAmlMeshService;
use Modules\Integration\Application\Services\AiGenerativeCopilotService;
use Modules\Integration\Application\Services\AiHumanAccountabilityService;
use Modules\Integration\Application\Services\AiModelGuardrailService;
use Modules\Integration\Application\Services\AiOptimizationEngineService;
use Modules\Integration\Application\Services\AirlineNetworkService;
use Modules\Integration\Application\Services\AnalyticsFederationService;
use Modules\Integration\Application\Services\AnalyticsModelMonitoringService;
use Modules\Integration\Application\Services\ApiIntegrationQualityGatesService;
use Modules\Integration\Application\Services\AquacultureExportService;
use Modules\Integration\Application\Services\ArchitectureFitnessMonolithHealthService;
use Modules\Integration\Application\Services\AssetAvailabilityProgramService;
use Modules\Integration\Application\Services\AssetProjectCapitalLifecycleService;
use Modules\Integration\Application\Services\AssetReliabilityService;
use Modules\Integration\Application\Services\AutomationControlPlaneRemediationService;
use Modules\Integration\Application\Services\AutonomousEnterpriseLadderService;
use Modules\Integration\Application\Services\AutonomousFieldFleetService;
use Modules\Integration\Application\Services\AviationService;
use Modules\Integration\Application\Services\B2bIndustryEcosystemPlatformService;
use Modules\Integration\Application\Services\BiodiversityLandUseProgramService;
use Modules\Integration\Application\Services\BmtMicrofinanceService;
use Modules\Integration\Application\Services\BoardGovernanceDoaService;
use Modules\Integration\Application\Services\BoardManagementReportingIntegrityService;
use Modules\Integration\Application\Services\BusinessContinuityCrisisService;
use Modules\Integration\Application\Services\BusinessContinuityCrisisSimulationService;
use Modules\Integration\Application\Services\BusinessEthicsAntiCorruptionService;
use Modules\Integration\Application\Services\BusinessKpiObservabilityService;
use Modules\Integration\Application\Services\BusinessLineTransitionPlansService;
use Modules\Integration\Application\Services\BusinessProcessOrchestrationService;
use Modules\Integration\Application\Services\CampusEducationService;
use Modules\Integration\Application\Services\CapacityCertificationReadinessService;
use Modules\Integration\Application\Services\CapitalAllocationPortfolioService;
use Modules\Integration\Application\Services\CapitalFundingStrategyService;
use Modules\Integration\Application\Services\CaseLoyaltyUnificationService;
use Modules\Integration\Application\Services\CashForecastingLiquidityCommandService;
use Modules\Integration\Application\Services\CircularBusinessModelsRevenueService;
use Modules\Integration\Application\Services\CircularEconomyService;
use Modules\Integration\Application\Services\CircularityWasteProgramService;
use Modules\Integration\Application\Services\CircularityWaterNatureService;
use Modules\Integration\Application\Services\ClimateAdaptationResilienceService;
use Modules\Integration\Application\Services\ClimateDecarbonizationRoadmapService;
use Modules\Integration\Application\Services\ClimateRiskInsuranceResilienceService;
use Modules\Integration\Application\Services\ClimateTargetsAllocationService;
use Modules\Integration\Application\Services\ClimateTransitionFinanceService;
use Modules\Integration\Application\Services\CoalitionLoyaltyBreakageService;
use Modules\Integration\Application\Services\ColdChainHighValueLogisticsService;
use Modules\Integration\Application\Services\CommercialRevenueGrowthPlanningService;
use Modules\Integration\Application\Services\CommonAuditReconciliationService;
use Modules\Integration\Application\Services\CommunityUgcSocialCommerceService;
use Modules\Integration\Application\Services\CommunityValueSocialProcurementService;
use Modules\Integration\Application\Services\CompensationBenefitsService;
use Modules\Integration\Application\Services\CompensationGovernancePayEquityService;
use Modules\Integration\Application\Services\ConcurrencyLockingService;
use Modules\Integration\Application\Services\ConglomerateSimulationService;
use Modules\Integration\Application\Services\ContinuousControlsMonitoringService;
use Modules\Integration\Application\Services\CorporateTaxEngineService;
use Modules\Integration\Application\Services\CorporateVentureIncubationService;
use Modules\Integration\Application\Services\CostCapacityValueGovernanceService;
use Modules\Integration\Application\Services\CostEfficiencyPerformanceService;
use Modules\Integration\Application\Services\CpqOrderToCashService;
use Modules\Integration\Application\Services\CrisisContinuityService;
use Modules\Integration\Application\Services\CrisisMegaScenarioService;
use Modules\Integration\Application\Services\CriticalLeadershipCoverageService;
use Modules\Integration\Application\Services\CrossBorderPayrollService;
use Modules\Integration\Application\Services\CrossLineProcessMeshService;
use Modules\Integration\Application\Services\CrossLineServiceBundlesService;
use Modules\Integration\Application\Services\CryptoNativeDefiSimulationService;
use Modules\Integration\Application\Services\CustomerCrm360Service;
use Modules\Integration\Application\Services\CustomerDataPlatformActivationService;
use Modules\Integration\Application\Services\CustomerLoyaltySubscriptionEconomyService;
use Modules\Integration\Application\Services\CustomerPricingFairnessService;
use Modules\Integration\Application\Services\CustomerServiceAgenticCommerceService;
use Modules\Integration\Application\Services\CxMetricsVocOrchestrationService;
use Modules\Integration\Application\Services\CyberRansomwareRecoveryDrillService;
use Modules\Integration\Application\Services\CyberResilienceService;
use Modules\Integration\Application\Services\DataAccessDomainSelfService;
use Modules\Integration\Application\Services\DatabasePartitionScaleService;
use Modules\Integration\Application\Services\DataGovernanceLineageService;
use Modules\Integration\Application\Services\DataMeshFederatedGovernanceService;
use Modules\Integration\Application\Services\DataModelOpsGovernanceService;
use Modules\Integration\Application\Services\DataPlatformService;
use Modules\Integration\Application\Services\DataProductsMonetizationService;
use Modules\Integration\Application\Services\DataQualityDriftLoadService;
use Modules\Integration\Application\Services\DataResilienceMigrationService;
use Modules\Integration\Application\Services\DataValueCostTransparencyService;
use Modules\Integration\Application\Services\DecisionIntelligencePlatformService;
use Modules\Integration\Application\Services\DecisionOptimizationGovernanceService;
use Modules\Integration\Application\Services\DesignSystemAccessibilityService;
use Modules\Integration\Application\Services\DeveloperExperienceQualityService;
use Modules\Integration\Application\Services\DeveloperProductivityEngineeringService;
use Modules\Integration\Application\Services\DigitalProductExperimentationService;
use Modules\Integration\Application\Services\DigitalSecuritiesCapitalMarketsService;
use Modules\Integration\Application\Services\DisasterRecoveryProofService;
use Modules\Integration\Application\Services\DistributedTransactionSafetyService;
use Modules\Integration\Application\Services\DistributorRetailerCollaborationService;
use Modules\Integration\Application\Services\DocumentRecordAutomationService;
use Modules\Integration\Application\Services\DomainCapacityEnvelopesService;
use Modules\Integration\Application\Services\DomainGovernanceService;
use Modules\Integration\Application\Services\DynamicMarketplaceC2cCommerceService;
use Modules\Integration\Application\Services\EcosystemDaoGovernanceService;
use Modules\Integration\Application\Services\EcosystemHealthNetworkGovernanceService;
use Modules\Integration\Application\Services\EdgeModelRegistryRolloutService;
use Modules\Integration\Application\Services\EducationCredentialAuthorizationService;
use Modules\Integration\Application\Services\EgovRegulatoryDigitalServicesService;
use Modules\Integration\Application\Services\EmbeddedInsuranceService;
use Modules\Integration\Application\Services\EndToEndFinanceService;
use Modules\Integration\Application\Services\EndToEndOrderServiceOrchestrationService;
use Modules\Integration\Application\Services\EndToEndRiskService;
use Modules\Integration\Application\Services\EndToEndSupplyChainService;
use Modules\Integration\Application\Services\EndToEndTalentService;
use Modules\Integration\Application\Services\EnergyDatacenterResilienceService;
use Modules\Integration\Application\Services\EnterpriseAccountGovernanceService;
use Modules\Integration\Application\Services\EnterpriseAiGovernanceOperatingModelService;
use Modules\Integration\Application\Services\EnterpriseArchitectureGovernanceService;
use Modules\Integration\Application\Services\EnterpriseCustomerValueGovernanceService;
use Modules\Integration\Application\Services\EnterpriseDataMigrationRetirementService;
use Modules\Integration\Application\Services\EnterpriseDigitalTrustService;
use Modules\Integration\Application\Services\EnterpriseEthicsSocialLicenseService;
use Modules\Integration\Application\Services\EnterpriseFinancialControlAssuranceService;
use Modules\Integration\Application\Services\EnterpriseFinancialIntegrityService;
use Modules\Integration\Application\Services\EnterpriseFutureReadinessService;
use Modules\Integration\Application\Services\EnterpriseIdentityZeroTrustService;
use Modules\Integration\Application\Services\EnterpriseInnovationRdGovernanceService;
use Modules\Integration\Application\Services\EnterpriseLearningFlywheelService;
use Modules\Integration\Application\Services\EnterpriseMasterDataGovernanceService;
use Modules\Integration\Application\Services\EnterpriseOperatingModelReadinessService;
use Modules\Integration\Application\Services\EnterprisePerformanceManagementService;
use Modules\Integration\Application\Services\EnterprisePolicyEngineService;
use Modules\Integration\Application\Services\EnterprisePolicySimulationService;
use Modules\Integration\Application\Services\EnterpriseProcessIntegrityService;
use Modules\Integration\Application\Services\EnterpriseQualityGovernanceService;
use Modules\Integration\Application\Services\EnterpriseResilienceAntiFragilityService;
use Modules\Integration\Application\Services\EnterpriseRiskAppetiteBoardReportingService;
use Modules\Integration\Application\Services\EnterpriseRiskService;
use Modules\Integration\Application\Services\EnterpriseSearchKnowledgeDocOpsService;
use Modules\Integration\Application\Services\EnterpriseSearchKnowledgeGraphService;
use Modules\Integration\Application\Services\EnterpriseServiceManagementCmdbService;
use Modules\Integration\Application\Services\EnterpriseStakeholderValueReportingService;
use Modules\Integration\Application\Services\EnterpriseSupplyChainGovernanceService;
use Modules\Integration\Application\Services\EnterpriseSustainabilityGovernanceService;
use Modules\Integration\Application\Services\EsgAssuranceDisclosureControlService;
use Modules\Integration\Application\Services\EsgClimateDisclosureControlService;
use Modules\Integration\Application\Services\EsgDataAssuranceDigitalReportingService;
use Modules\Integration\Application\Services\EsgDataFabricService;
use Modules\Integration\Application\Services\EsgHumanRightsJustTransitionService;
use Modules\Integration\Application\Services\EsgImpactAuditScaleService;
use Modules\Integration\Application\Services\EsgOperatingModelOwnershipService;
use Modules\Integration\Application\Services\EthicalSourcingService;
use Modules\Integration\Application\Services\EthicsComplianceMaturityService;
use Modules\Integration\Application\Services\EventDrivenCqrsSagaService;
use Modules\Integration\Application\Services\EventSpineReplayCenterService;
use Modules\Integration\Application\Services\FashionRetailCircularService;
use Modules\Integration\Application\Services\FashionSourcingService;
use Modules\Integration\Application\Services\FederatedEdgeAiOperationsService;
use Modules\Integration\Application\Services\FieldRemoteSiteOperationsIntegrityService;
use Modules\Integration\Application\Services\FieldServiceSlaService;
use Modules\Integration\Application\Services\FinanceCloseAgilityService;
use Modules\Integration\Application\Services\FinancialCrimeSanctionsService;
use Modules\Integration\Application\Services\FintechInsurtechPartnerService;
use Modules\Integration\Application\Services\FleetAssetUtilizationOptimizationService;
use Modules\Integration\Application\Services\FoodBrandNutritionService;
use Modules\Integration\Application\Services\FoodProcessingService;
use Modules\Integration\Application\Services\ForestryTimberService;
use Modules\Integration\Application\Services\FpaDriverBasedBudgetingService;
use Modules\Integration\Application\Services\FraudRiskAssessmentDetectionService;
use Modules\Integration\Application\Services\FulfillmentOrchestrationPromiseService;
use Modules\Integration\Application\Services\FullInsuranceService;
use Modules\Integration\Application\Services\GenerativeEngineeringCopilotService;
use Modules\Integration\Application\Services\GlobalCommandService;
use Modules\Integration\Application\Services\GlobalFinanceTreasuryRiskService;
use Modules\Integration\Application\Services\GlobalPayrollCloseReconciliationService;
use Modules\Integration\Application\Services\GlobalSearchService;
use Modules\Integration\Application\Services\GoldenScenarioMegaAuditService;
use Modules\Integration\Application\Services\GovernanceDataRetentionDiscoveryService;
use Modules\Integration\Application\Services\GovEthicsAiBiometricsService;
use Modules\Integration\Application\Services\GovInternalAuditAssuranceService;
use Modules\Integration\Application\Services\GovTrustServicesSignaturesService;
use Modules\Integration\Application\Services\GreenProcurementLeaseChoiceService;
use Modules\Integration\Application\Services\GreenProcurementSupplierDevelopmentService;
use Modules\Integration\Application\Services\GroupCommandCenterService;
use Modules\Integration\Application\Services\GroupFinanceOperatingModelService;
use Modules\Integration\Application\Services\HealthInsuranceWellbeingService;
use Modules\Integration\Application\Services\HospitalityOperationsPlaybookService;
use Modules\Integration\Application\Services\HumanAiCollaborationWorkflowsService;
use Modules\Integration\Application\Services\IdentityTenancyService;
use Modules\Integration\Application\Services\InstitutionalMemoryKnowledgeService;
use Modules\Integration\Application\Services\InsuranceSyariahSecuritiesFinanceService;
use Modules\Integration\Application\Services\IntegrationService;
use Modules\Integration\Application\Services\InternalCapabilitiesMarketplaceService;
use Modules\Integration\Application\Services\InternalControlMaturityService;
use Modules\Integration\Application\Services\InternalControlSodService;
use Modules\Integration\Application\Services\InvestorLenderReportingService;
use Modules\Integration\Application\Services\InvestorRelationsService;
use Modules\Integration\Application\Services\IslamicTradeFinanceService;
use Modules\Integration\Application\Services\JourneyAnalyticsOptimizationService;
use Modules\Integration\Application\Services\KamPartnershipRevenueService;
use Modules\Integration\Application\Services\KnowledgeGraphEnterpriseCopilotService;
use Modules\Integration\Application\Services\KnowledgeGroundingCitationService;
use Modules\Integration\Application\Services\LeadershipPipelineExecutiveService;
use Modules\Integration\Application\Services\LearningOperationsEffectivenessService;
use Modules\Integration\Application\Services\LearningPlatformService;
use Modules\Integration\Application\Services\LearningSkillIntelligenceService;
use Modules\Integration\Application\Services\LegalOperationsService;
use Modules\Integration\Application\Services\LegalRegulatoryChangeExecutionService;
use Modules\Integration\Application\Services\LifeHealthWellnessService;
use Modules\Integration\Application\Services\MaintenanceReliabilityGovernanceService;
use Modules\Integration\Application\Services\MarineAquacultureService;
use Modules\Integration\Application\Services\MarketDisruptionSimulationService;
use Modules\Integration\Application\Services\MarketingAutomationAttributionService;
use Modules\Integration\Application\Services\MarketplaceDisputeBuyerProtectionService;
use Modules\Integration\Application\Services\MediaCommerceContentRightsService;
use Modules\Integration\Application\Services\MegaScenarioService;
use Modules\Integration\Application\Services\MiningPortCommodityFlowService;
use Modules\Integration\Application\Services\MnaDueDiligencePmiService;
use Modules\Integration\Application\Services\MnaMegaScenarioRestructuringService;
use Modules\Integration\Application\Services\ModelIncidentSafetyCaseService;
use Modules\Integration\Application\Services\MultiModalVisionIntegrationService;
use Modules\Integration\Application\Services\MultiRegionEdgeArchitectureService;
use Modules\Integration\Application\Services\NatureFinanceService;
use Modules\Integration\Application\Services\NatureWaterCommunityFinanceService;
use Modules\Integration\Application\Services\NetworkResilienceChaosService;
use Modules\Integration\Application\Services\ObservabilitySloCapacityService;
use Modules\Integration\Application\Services\ObservabilitySloEconomyService;
use Modules\Integration\Application\Services\OceanFleetService;
use Modules\Integration\Application\Services\OmnichannelServiceConsistencySlaService;
use Modules\Integration\Application\Services\OperationsExcellenceGovernanceService;
use Modules\Integration\Application\Services\OperationsExcellenceService;
use Modules\Integration\Application\Services\OrgDesignChangeManagementService;
use Modules\Integration\Application\Services\OrgDesignWorkforcePlanningService;
use Modules\Integration\Application\Services\PartitionArchiveService;
use Modules\Integration\Application\Services\PartnerApiEconomicsBillingService;
use Modules\Integration\Application\Services\PartnerCosellAffiliateService;
use Modules\Integration\Application\Services\PartnerOnboardingEcosystemService;
use Modules\Integration\Application\Services\PerformanceCostOptimizationService;
use Modules\Integration\Application\Services\PerformanceEngagementAnalyticsService;
use Modules\Integration\Application\Services\PerformanceRewardsTalentDecisionsService;
use Modules\Integration\Application\Services\PlanningSchedulingUnificationService;
use Modules\Integration\Application\Services\PlatformAutomatedOpsFinopsService;
use Modules\Integration\Application\Services\PlatformEconomyService;
use Modules\Integration\Application\Services\PlatformFeatureFlagsParityService;
use Modules\Integration\Application\Services\PlatformFinalStressSecuritySimulationService;
use Modules\Integration\Application\Services\PlatformMonolithEvolutionService;
use Modules\Integration\Application\Services\PlatformRelease300HandoverService;
use Modules\Integration\Application\Services\PlatformReleaseCandidateDocsService;
use Modules\Integration\Application\Services\PolicyComplianceTestingRemediationService;
use Modules\Integration\Application\Services\PortOperationsService;
use Modules\Integration\Application\Services\PredictiveOperationsDigitalTwinService;
use Modules\Integration\Application\Services\PricingScienceRevenueOptimizationService;
use Modules\Integration\Application\Services\PrivacyEngineeringDataProductsService;
use Modules\Integration\Application\Services\PrivacyVaultService;
use Modules\Integration\Application\Services\ProblemManagementRootCauseService;
use Modules\Integration\Application\Services\ProductLifecycleCircularDesignService;
use Modules\Integration\Application\Services\ProductStewardshipEprService;
use Modules\Integration\Application\Services\ProfessionalServicesService;
use Modules\Integration\Application\Services\ProfitabilityCostIntelligenceService;
use Modules\Integration\Application\Services\ProjectPortfolioManagementService;
use Modules\Integration\Application\Services\PublicAffairsLicenseService;
use Modules\Integration\Application\Services\QualityAssuranceInspectionProgramService;
use Modules\Integration\Application\Services\QualityEngineeringAutomationService;
use Modules\Integration\Application\Services\QualityManagementSystemService;
use Modules\Integration\Application\Services\QueueSchedulerBatchService;
use Modules\Integration\Application\Services\ReadWriteReplicaLagService;
use Modules\Integration\Application\Services\RealtimeStreamProcessingService;
use Modules\Integration\Application\Services\RegulatoryChangeMegaScenarioService;
use Modules\Integration\Application\Services\RegulatoryComplianceService;
use Modules\Integration\Application\Services\RegulatoryPolicyLifecycleService;
use Modules\Integration\Application\Services\RegulatoryTaxOperationsService;
use Modules\Integration\Application\Services\ReinsuranceAndCatService;
use Modules\Integration\Application\Services\ReleaseManagementChangeAdvisoryService;
use Modules\Integration\Application\Services\ReleaseTrainDeploymentSafetyService;
use Modules\Integration\Application\Services\ResilienceWave2Service;
use Modules\Integration\Application\Services\RndTechTransferService;
use Modules\Integration\Application\Services\SafetyCertifiedPermitAccessService;
use Modules\Integration\Application\Services\SalesForcePipelineExcellenceService;
use Modules\Integration\Application\Services\ScaleBenchmarkService;
use Modules\Integration\Application\Services\SdmOrgHealthCultureService;
use Modules\Integration\Application\Services\SdmWellnessOccupationalHealthService;
use Modules\Integration\Application\Services\SecurityEngineeringSupplyChainIntegrityService;
use Modules\Integration\Application\Services\SecurityPenetrationRegressionService;
use Modules\Integration\Application\Services\ServiceCatalogDeveloperPortalService;
use Modules\Integration\Application\Services\ServiceLifecycleSunsetService;
use Modules\Integration\Application\Services\ServiceOncallSloGovernanceService;
use Modules\Integration\Application\Services\ServiceRecoveryLoyaltyProtectionService;
use Modules\Integration\Application\Services\SimulationSyntheticFactoryService;
use Modules\Integration\Application\Services\SkillsEconomyInternalMobilityService;
use Modules\Integration\Application\Services\SmartDistrictService;
use Modules\Integration\Application\Services\SocialImpactCommunityProgramService;
use Modules\Integration\Application\Services\StrategicPlanningExecutionService;
use Modules\Integration\Application\Services\StrategicWorkforceCapabilityService;
use Modules\Integration\Application\Services\StressBenchmarkBaselineService;
use Modules\Integration\Application\Services\SubscriptionBillingRetentionService;
use Modules\Integration\Application\Services\SubscriptionCommerceReplenishmentService;
use Modules\Integration\Application\Services\SukukAndZakatService;
use Modules\Integration\Application\Services\SuperAppMiniAppPlatformService;
use Modules\Integration\Application\Services\SupplierCollaborativeSourcingService;
use Modules\Integration\Application\Services\SupplierFinanceCollaborativePlanningService;
use Modules\Integration\Application\Services\SupplyChainGovernanceScorecardsService;
use Modules\Integration\Application\Services\SupplyChainNetworkService;
use Modules\Integration\Application\Services\SupplyChainResilienceService;
use Modules\Integration\Application\Services\SupplyChainTraceabilityService;
use Modules\Integration\Application\Services\SupplyChainTradeMaterialFlowsService;
use Modules\Integration\Application\Services\SustainabilityFinanceDataService;
use Modules\Integration\Application\Services\SustainableFinanceReportingService;
use Modules\Integration\Application\Services\SyariahBankingService;
use Modules\Integration\Application\Services\SyariahOperationsService;
use Modules\Integration\Application\Services\SyntheticDataTrainingGovernanceService;
use Modules\Integration\Application\Services\TakafulAndAgriService;
use Modules\Integration\Application\Services\TalentAcquisitionEmployerBrandService;
use Modules\Integration\Application\Services\TalentLifecycleService;
use Modules\Integration\Application\Services\TalentValueOrganizationalOutcomesService;
use Modules\Integration\Application\Services\TaxCustomsTradeService;
use Modules\Integration\Application\Services\TaxTransferPricingOperationsService;
use Modules\Integration\Application\Services\TelecomIdentityService;
use Modules\Integration\Application\Services\TenderBidManagementService;
use Modules\Integration\Application\Services\TestDataComplianceService;
use Modules\Integration\Application\Services\ThirdPartyEcosystemResilienceService;
use Modules\Integration\Application\Services\ThirdPartyRiskService;
use Modules\Integration\Application\Services\ThreatDetectionService;
use Modules\Integration\Application\Services\TotalWellbeingSustainabilityService;
use Modules\Integration\Application\Services\TreasuryAlgorithmicMarketRiskService;
use Modules\Integration\Application\Services\TreasuryUnificationService;
use Modules\Integration\Application\Services\TrustSafetyModerationProtectionService;
use Modules\Integration\Application\Services\UnifiedControlTowerDecisionService;
use Modules\Integration\Application\Services\UserResearchDesignSystemService;
use Modules\Integration\Application\Services\ValueChainSimulationService;
use Modules\Integration\Application\Services\WarehouseRoboticsAutomationService;
use Modules\Integration\Application\Services\WaterEnergyManagementService;
use Modules\Integration\Application\Services\WhistleblowingEthicsService;
use Modules\Integration\Application\Services\WhistleblowingEthicsSpeakUpService;
use Modules\Integration\Application\Services\WorkforceAutomationRoleDesignService;
use Modules\Integration\Application\Services\WorkforceLaborComplianceIntegrityService;
use Modules\Integration\Application\Services\WorkforceSkillsOperatingCapacityService;
use Modules\Integration\Application\Services\WorkingCapitalScfService;
use Modules\Integration\Application\Services\ZeroTrustService;
use Modules\Integration\Console\Commands\AuditIntegrationCommand;
use Modules\Integration\Console\Commands\DrAuditCommand;
use Modules\Integration\Console\Commands\SecurityAuditCommand;
use Modules\Shared\Application\MenuRegistry;

class IntegrationServiceProvider extends ServiceProvider
{
    public function register(): void
    {
        $this->app->singleton(IntegrationService::class);
        $this->app->singleton(ZeroTrustService::class);
        $this->app->singleton(PrivacyVaultService::class);
        $this->app->singleton(RegulatoryComplianceService::class);
        $this->app->singleton(ThreatDetectionService::class);
        $this->app->singleton(SecurityPenTestService::class);
        $this->app->singleton(ResilienceWave2Service::class);
        $this->app->singleton(DataPlatformService::class);
        $this->app->singleton(PlatformEconomyService::class);
        $this->app->singleton(MegaScenarioService::class);
        $this->app->singleton(GlobalCommandService::class);
        $this->app->singleton(CrossBorderPayrollService::class);
        $this->app->singleton(SupplyChainResilienceService::class);
        $this->app->singleton(EthicalSourcingService::class);
        $this->app->singleton(CrisisContinuityService::class);
        $this->app->singleton(FullInsuranceService::class);
        $this->app->singleton(ReinsuranceAndCatService::class);
        $this->app->singleton(EmbeddedInsuranceService::class);
        $this->app->singleton(LifeHealthWellnessService::class);
        $this->app->singleton(TakafulAndAgriService::class);
        $this->app->singleton(SyariahBankingService::class);
        $this->app->singleton(SukukAndZakatService::class);
        $this->app->singleton(BmtMicrofinanceService::class);
        $this->app->singleton(IslamicTradeFinanceService::class);
        $this->app->singleton(SyariahOperationsService::class);
        $this->app->singleton(CampusEducationService::class);
        $this->app->singleton(LearningPlatformService::class);
        $this->app->singleton(FoodProcessingService::class);
        $this->app->singleton(FoodBrandNutritionService::class);
        $this->app->singleton(MarineAquacultureService::class);
        $this->app->singleton(AquacultureExportService::class);
        $this->app->singleton(ForestryTimberService::class);
        $this->app->singleton(NatureFinanceService::class);
        $this->app->singleton(CircularEconomyService::class);
        $this->app->singleton(ProfessionalServicesService::class);
        $this->app->singleton(LegalOperationsService::class);
        $this->app->singleton(AviationService::class);
        $this->app->singleton(AirlineNetworkService::class);
        $this->app->singleton(PortOperationsService::class);
        $this->app->singleton(OceanFleetService::class);
        $this->app->singleton(FashionSourcingService::class);
        $this->app->singleton(FashionRetailCircularService::class);
        $this->app->singleton(TelecomIdentityService::class);
        $this->app->singleton(SmartDistrictService::class);
        $this->app->singleton(DomainGovernanceService::class);
        $this->app->singleton(ValueChainSimulationService::class);
        $this->app->singleton(TreasuryUnificationService::class);
        $this->app->singleton(IdentityTenancyService::class);
        $this->app->singleton(AnalyticsFederationService::class);
        $this->app->singleton(GroupCommandCenterService::class);
        $this->app->singleton(ScaleBenchmarkService::class);
        $this->app->singleton(PartitionArchiveService::class);
        $this->app->singleton(ConcurrencyLockingService::class);
        $this->app->singleton(GlobalSearchService::class);
        $this->app->singleton(AiModelGuardrailService::class);
        $this->app->singleton(AgentHitlOrchestrationService::class);
        $this->app->singleton(AiDecisionAuditService::class);
        $this->app->singleton(AiGenerativeCopilotService::class);
        $this->app->singleton(AiOptimizationEngineService::class);
        $this->app->singleton(AiFraudAmlMeshService::class);
        $this->app->singleton(AiForecastingSopService::class);
        $this->app->singleton(EnterpriseRiskService::class);
        $this->app->singleton(InternalControlSodService::class);
        $this->app->singleton(CyberResilienceService::class);
        $this->app->singleton(ThirdPartyRiskService::class);
        $this->app->singleton(BusinessContinuityCrisisService::class);
        $this->app->singleton(RegulatoryPolicyLifecycleService::class);
        $this->app->singleton(TaxCustomsTradeService::class);
        $this->app->singleton(FinanceCloseAgilityService::class);
        $this->app->singleton(CapitalFundingStrategyService::class);
        $this->app->singleton(InvestorRelationsService::class);
        $this->app->singleton(ProfitabilityCostIntelligenceService::class);
        $this->app->singleton(QualityManagementSystemService::class);
        $this->app->singleton(AssetReliabilityService::class);
        $this->app->singleton(SupplyChainNetworkService::class);
        $this->app->singleton(FieldServiceSlaService::class);
        $this->app->singleton(ProjectPortfolioManagementService::class);
        $this->app->singleton(RndTechTransferService::class);
        $this->app->singleton(CustomerCrm360Service::class);
        $this->app->singleton(CaseLoyaltyUnificationService::class);
        $this->app->singleton(SubscriptionBillingRetentionService::class);
        $this->app->singleton(MarketingAutomationAttributionService::class);
        $this->app->singleton(OrgDesignWorkforcePlanningService::class);
        $this->app->singleton(CompensationBenefitsService::class);
        $this->app->singleton(TalentLifecycleService::class);
        $this->app->singleton(PerformanceEngagementAnalyticsService::class);
        $this->app->singleton(LearningSkillIntelligenceService::class);
        $this->app->singleton(EsgDataFabricService::class);
        $this->app->singleton(ClimateDecarbonizationRoadmapService::class);
        $this->app->singleton(CircularityWaterNatureService::class);
        $this->app->singleton(BoardGovernanceDoaService::class);
        $this->app->singleton(WhistleblowingEthicsService::class);
        $this->app->singleton(EcosystemDaoGovernanceService::class);
        $this->app->singleton(CorporateVentureIncubationService::class);
        $this->app->singleton(InternalCapabilitiesMarketplaceService::class);
        $this->app->singleton(DigitalProductExperimentationService::class);
        $this->app->singleton(DeveloperExperienceQualityService::class);
        $this->app->singleton(ReleaseTrainDeploymentSafetyService::class);
        $this->app->singleton(PerformanceCostOptimizationService::class);
        $this->app->singleton(DesignSystemAccessibilityService::class);
        $this->app->singleton(DataGovernanceLineageService::class);
        $this->app->singleton(RealtimeStreamProcessingService::class);
        $this->app->singleton(AdvancedAnalyticsGraphResearchService::class);
        $this->app->singleton(DataProductsMonetizationService::class);
        $this->app->singleton(PricingScienceRevenueOptimizationService::class);
        $this->app->singleton(SalesForcePipelineExcellenceService::class);
        $this->app->singleton(KamPartnershipRevenueService::class);
        $this->app->singleton(TenderBidManagementService::class);
        $this->app->singleton(CpqOrderToCashService::class);
        $this->app->singleton(CxMetricsVocOrchestrationService::class);
        $this->app->singleton(EndToEndSupplyChainService::class);
        $this->app->singleton(EndToEndFinanceService::class);
        $this->app->singleton(EndToEndRiskService::class);
        $this->app->singleton(EndToEndTalentService::class);
        $this->app->singleton(GoldenScenarioMegaAuditService::class);
        $this->app->singleton(ObservabilitySloEconomyService::class);
        $this->app->singleton(EventDrivenCqrsSagaService::class);
        $this->app->singleton(MultiRegionEdgeArchitectureService::class);
        $this->app->singleton(EnterpriseSearchKnowledgeGraphService::class);
        $this->app->singleton(PartnerCosellAffiliateService::class);
        $this->app->singleton(SupplierFinanceCollaborativePlanningService::class);
        $this->app->singleton(DistributorRetailerCollaborationService::class);
        $this->app->singleton(EgovRegulatoryDigitalServicesService::class);
        $this->app->singleton(FintechInsurtechPartnerService::class);
        $this->app->singleton(AcademicIndustryResearchService::class);
        $this->app->singleton(DecisionIntelligencePlatformService::class);
        $this->app->singleton(DataMeshFederatedGovernanceService::class);
        $this->app->singleton(AutonomousEnterpriseLadderService::class);
        $this->app->singleton(SimulationSyntheticFactoryService::class);
        $this->app->singleton(HumanAiCollaborationWorkflowsService::class);
        $this->app->singleton(DigitalSecuritiesCapitalMarketsService::class);
        $this->app->singleton(CryptoNativeDefiSimulationService::class);
        $this->app->singleton(FinancialCrimeSanctionsService::class);
        $this->app->singleton(CorporateTaxEngineService::class);
        $this->app->singleton(CashForecastingLiquidityCommandService::class);
        $this->app->singleton(OperationsExcellenceService::class);
        $this->app->singleton(PlanningSchedulingUnificationService::class);
        $this->app->singleton(FleetAssetUtilizationOptimizationService::class);
        $this->app->singleton(WarehouseRoboticsAutomationService::class);
        $this->app->singleton(HospitalityOperationsPlaybookService::class);
        $this->app->singleton(OmnichannelServiceConsistencySlaService::class);
        $this->app->singleton(CommunityUgcSocialCommerceService::class);
        $this->app->singleton(CoalitionLoyaltyBreakageService::class);
        $this->app->singleton(SdmOrgHealthCultureService::class);
        $this->app->singleton(SdmWellnessOccupationalHealthService::class);
        $this->app->singleton(EsgImpactAuditScaleService::class);
        $this->app->singleton(ClimateAdaptationResilienceService::class);
        $this->app->singleton(EsgHumanRightsJustTransitionService::class);
        $this->app->singleton(ProductStewardshipEprService::class);
        $this->app->singleton(EnterprisePolicyEngineService::class);
        $this->app->singleton(GovernanceDataRetentionDiscoveryService::class);
        $this->app->singleton(GovTrustServicesSignaturesService::class);
        $this->app->singleton(GovInternalAuditAssuranceService::class);
        $this->app->singleton(GovEthicsAiBiometricsService::class);
        $this->app->singleton(PlatformMonolithEvolutionService::class);
        $this->app->singleton(PlatformFeatureFlagsParityService::class);
        $this->app->singleton(PlatformAutomatedOpsFinopsService::class);
        $this->app->singleton(PlatformFinalStressSecuritySimulationService::class);
        $this->app->singleton(PlatformReleaseCandidateDocsService::class);
        $this->app->singleton(PlatformRelease300HandoverService::class);
        $this->app->singleton(AdvancedSupplyOptimizationService::class);
        $this->app->singleton(SupplierCollaborativeSourcingService::class);
        $this->app->singleton(ColdChainHighValueLogisticsService::class);
        $this->app->singleton(FulfillmentOrchestrationPromiseService::class);
        $this->app->singleton(CommercialRevenueGrowthPlanningService::class);
        $this->app->singleton(AutonomousFieldFleetService::class);
        $this->app->singleton(PredictiveOperationsDigitalTwinService::class);
        $this->app->singleton(NetworkResilienceChaosService::class);
        $this->app->singleton(TreasuryAlgorithmicMarketRiskService::class);
        $this->app->singleton(WorkingCapitalScfService::class);
        $this->app->singleton(ContinuousControlsMonitoringService::class);
        $this->app->singleton(FpaDriverBasedBudgetingService::class);
        $this->app->singleton(DynamicMarketplaceC2cCommerceService::class);
        $this->app->singleton(SubscriptionCommerceReplenishmentService::class);
        $this->app->singleton(SuperAppMiniAppPlatformService::class);
        $this->app->singleton(B2bIndustryEcosystemPlatformService::class);
        $this->app->singleton(SkillsEconomyInternalMobilityService::class);
        $this->app->singleton(LeadershipPipelineExecutiveService::class);
        $this->app->singleton(WorkforceAutomationRoleDesignService::class);
        $this->app->singleton(TotalWellbeingSustainabilityService::class);
        $this->app->singleton(StrategicWorkforceCapabilityService::class);
        $this->app->singleton(GlobalPayrollCloseReconciliationService::class);
        $this->app->singleton(SafetyCertifiedPermitAccessService::class);
        $this->app->singleton(CriticalLeadershipCoverageService::class);
        $this->app->singleton(TalentValueOrganizationalOutcomesService::class);
        $this->app->singleton(ClimateTransitionFinanceService::class);
        $this->app->singleton(SupplyChainTraceabilityService::class);
        $this->app->singleton(ProductLifecycleCircularDesignService::class);
        $this->app->singleton(ClimateRiskInsuranceResilienceService::class);
        $this->app->singleton(NatureWaterCommunityFinanceService::class);
        $this->app->singleton(EsgAssuranceDisclosureControlService::class);
        $this->app->singleton(GreenProcurementLeaseChoiceService::class);
        $this->app->singleton(BusinessLineTransitionPlansService::class);
        $this->app->singleton(CircularBusinessModelsRevenueService::class);
        $this->app->singleton(CommunityValueSocialProcurementService::class);
        $this->app->singleton(EnterprisePolicySimulationService::class);
        $this->app->singleton(EthicsComplianceMaturityService::class);
        $this->app->singleton(LegalRegulatoryChangeExecutionService::class);
        $this->app->singleton(PublicAffairsLicenseService::class);
        $this->app->singleton(BusinessEthicsAntiCorruptionService::class);
        $this->app->singleton(PrivacyEngineeringDataProductsService::class);
        $this->app->singleton(DataValueCostTransparencyService::class);
        $this->app->singleton(DataResilienceMigrationService::class);
        $this->app->singleton(DataAccessDomainSelfService::class);
        $this->app->singleton(AnalyticsModelMonitoringService::class);
        $this->app->singleton(AgentSafetyGuardrailsService::class);
        $this->app->singleton(KnowledgeGroundingCitationService::class);
        $this->app->singleton(DecisionOptimizationGovernanceService::class);
        $this->app->singleton(AiCostSustainabilityService::class);
        $this->app->singleton(AiHumanAccountabilityService::class);
        $this->app->singleton(MultiModalVisionIntegrationService::class);
        $this->app->singleton(GenerativeEngineeringCopilotService::class);
        $this->app->singleton(CustomerServiceAgenticCommerceService::class);
        $this->app->singleton(FederatedEdgeAiOperationsService::class);
        $this->app->singleton(EdgeModelRegistryRolloutService::class);
        $this->app->singleton(ModelIncidentSafetyCaseService::class);
        $this->app->singleton(KnowledgeGraphEnterpriseCopilotService::class);
        $this->app->singleton(AgentMarketplaceGovernedToolsService::class);
        $this->app->singleton(SyntheticDataTrainingGovernanceService::class);
        $this->app->singleton(EnterpriseAiGovernanceOperatingModelService::class);
        $this->app->singleton(ServiceCatalogDeveloperPortalService::class);
        $this->app->singleton(EnterpriseServiceManagementCmdbService::class);
        $this->app->singleton(ServiceOncallSloGovernanceService::class);
        $this->app->singleton(AutomationControlPlaneRemediationService::class);
        $this->app->singleton(CostCapacityValueGovernanceService::class);
        $this->app->singleton(ServiceLifecycleSunsetService::class);
        $this->app->singleton(BusinessProcessOrchestrationService::class);
        $this->app->singleton(DocumentRecordAutomationService::class);
        $this->app->singleton(EventSpineReplayCenterService::class);
        $this->app->singleton(ArchitectureFitnessMonolithHealthService::class);
        $this->app->singleton(PartnerOnboardingEcosystemService::class);
        $this->app->singleton(PartnerApiEconomicsBillingService::class);
        $this->app->singleton(MarketplaceDisputeBuyerProtectionService::class);
        $this->app->singleton(TrustSafetyModerationProtectionService::class);
        $this->app->singleton(EcosystemHealthNetworkGovernanceService::class);
        $this->app->singleton(GlobalFinanceTreasuryRiskService::class);
        $this->app->singleton(AssetProjectCapitalLifecycleService::class);
        $this->app->singleton(CustomerLoyaltySubscriptionEconomyService::class);
        $this->app->singleton(WorkforceSkillsOperatingCapacityService::class);
        $this->app->singleton(SustainabilityFinanceDataService::class);
        $this->app->singleton(SupplyChainTradeMaterialFlowsService::class);
        $this->app->singleton(HealthInsuranceWellbeingService::class);
        $this->app->singleton(EnergyDatacenterResilienceService::class);
        $this->app->singleton(EducationCredentialAuthorizationService::class);
        $this->app->singleton(MediaCommerceContentRightsService::class);
        $this->app->singleton(MiningPortCommodityFlowService::class);
        $this->app->singleton(CrossLineProcessMeshService::class);
        $this->app->singleton(UnifiedControlTowerDecisionService::class);
        $this->app->singleton(CommonAuditReconciliationService::class);
        $this->app->singleton(CrossLineServiceBundlesService::class);
        $this->app->singleton(StressBenchmarkBaselineService::class);
        $this->app->singleton(DomainCapacityEnvelopesService::class);
        $this->app->singleton(DatabasePartitionScaleService::class);
        $this->app->singleton(QueueSchedulerBatchService::class);
        $this->app->singleton(ReadWriteReplicaLagService::class);
        $this->app->singleton(DistributedTransactionSafetyService::class);
        $this->app->singleton(DataQualityDriftLoadService::class);
        $this->app->singleton(SecurityPenetrationRegressionService::class);
        $this->app->singleton(DisasterRecoveryProofService::class);
        $this->app->singleton(CapacityCertificationReadinessService::class);
        $this->app->singleton(InternalControlMaturityService::class);
        $this->app->singleton(FraudRiskAssessmentDetectionService::class);
        $this->app->singleton(ThirdPartyEcosystemResilienceService::class);
        $this->app->singleton(RegulatoryTaxOperationsService::class);
        $this->app->singleton(BoardManagementReportingIntegrityService::class);
        $this->app->singleton(WhistleblowingEthicsSpeakUpService::class);
        $this->app->singleton(EsgClimateDisclosureControlService::class);
        $this->app->singleton(OperationsExcellenceGovernanceService::class);
        $this->app->singleton(EndToEndOrderServiceOrchestrationService::class);
        $this->app->singleton(AssetAvailabilityProgramService::class);
        $this->app->singleton(FieldRemoteSiteOperationsIntegrityService::class);
        $this->app->singleton(QualityAssuranceInspectionProgramService::class);
        $this->app->singleton(MaintenanceReliabilityGovernanceService::class);
        $this->app->singleton(SupplyChainGovernanceScorecardsService::class);
        $this->app->singleton(WorkforceLaborComplianceIntegrityService::class);
        $this->app->singleton(CustomerDataPlatformActivationService::class);
        $this->app->singleton(JourneyAnalyticsOptimizationService::class);
        $this->app->singleton(ServiceRecoveryLoyaltyProtectionService::class);
        $this->app->singleton(CustomerPricingFairnessService::class);
        $this->app->singleton(EnterpriseAccountGovernanceService::class);
        $this->app->singleton(TalentAcquisitionEmployerBrandService::class);
        $this->app->singleton(CompensationGovernancePayEquityService::class);
        $this->app->singleton(PerformanceRewardsTalentDecisionsService::class);
        $this->app->singleton(LearningOperationsEffectivenessService::class);
        $this->app->singleton(OrgDesignChangeManagementService::class);
        $this->app->singleton(QualityEngineeringAutomationService::class);
        $this->app->singleton(ReleaseManagementChangeAdvisoryService::class);
        $this->app->singleton(ProblemManagementRootCauseService::class);
        $this->app->singleton(ApiIntegrationQualityGatesService::class);
        $this->app->singleton(SecurityEngineeringSupplyChainIntegrityService::class);
        $this->app->singleton(ObservabilitySloCapacityService::class);
        $this->app->singleton(DataModelOpsGovernanceService::class);
        $this->app->singleton(EnterpriseSearchKnowledgeDocOpsService::class);
        $this->app->singleton(CostEfficiencyPerformanceService::class);
        $this->app->singleton(UserResearchDesignSystemService::class);
        $this->app->singleton(GroupFinanceOperatingModelService::class);
        $this->app->singleton(CapitalAllocationPortfolioService::class);
        $this->app->singleton(TaxTransferPricingOperationsService::class);
        $this->app->singleton(InvestorLenderReportingService::class);
        $this->app->singleton(InsuranceSyariahSecuritiesFinanceService::class);
        $this->app->singleton(EsgOperatingModelOwnershipService::class);
        $this->app->singleton(ClimateTargetsAllocationService::class);
        $this->app->singleton(CircularityWasteProgramService::class);
        $this->app->singleton(SocialImpactCommunityProgramService::class);
        $this->app->singleton(BiodiversityLandUseProgramService::class);
        $this->app->singleton(WaterEnergyManagementService::class);
        $this->app->singleton(GreenProcurementSupplierDevelopmentService::class);
        $this->app->singleton(SustainableFinanceReportingService::class);
        $this->app->singleton(EsgDataAssuranceDigitalReportingService::class);
        $this->app->singleton(EnterpriseRiskAppetiteBoardReportingService::class);
        $this->app->singleton(PolicyComplianceTestingRemediationService::class);
        $this->app->singleton(BusinessContinuityCrisisSimulationService::class);
        $this->app->singleton(MnaDueDiligencePmiService::class);
        $this->app->singleton(StrategicPlanningExecutionService::class);
        $this->app->singleton(EnterpriseProcessIntegrityService::class);
        $this->app->singleton(EnterpriseMasterDataGovernanceService::class);
        $this->app->singleton(EnterpriseIdentityZeroTrustService::class);
        $this->app->singleton(EnterpriseFinancialControlAssuranceService::class);
        $this->app->singleton(EnterprisePerformanceManagementService::class);
        $this->app->singleton(EnterpriseInnovationRdGovernanceService::class);
        $this->app->singleton(EnterpriseSupplyChainGovernanceService::class);
        $this->app->singleton(EnterpriseQualityGovernanceService::class);
        $this->app->singleton(EnterpriseCustomerValueGovernanceService::class);
        $this->app->singleton(EnterpriseSustainabilityGovernanceService::class);
        $this->app->singleton(ConglomerateSimulationService::class);
        $this->app->singleton(CrisisMegaScenarioService::class);
        $this->app->singleton(MnaMegaScenarioRestructuringService::class);
        $this->app->singleton(RegulatoryChangeMegaScenarioService::class);
        $this->app->singleton(MarketDisruptionSimulationService::class);
        $this->app->singleton(CyberRansomwareRecoveryDrillService::class);
        $this->app->singleton(DeveloperProductivityEngineeringService::class);
        $this->app->singleton(EnterpriseArchitectureGovernanceService::class);
        $this->app->singleton(EnterpriseDataMigrationRetirementService::class);
        $this->app->singleton(TestDataComplianceService::class);
        $this->app->singleton(BusinessKpiObservabilityService::class);
        $this->app->singleton(InstitutionalMemoryKnowledgeService::class);
        $this->app->singleton(EnterpriseOperatingModelReadinessService::class);
        $this->app->singleton(EnterpriseStakeholderValueReportingService::class);
        $this->app->singleton(EnterpriseResilienceAntiFragilityService::class);
        $this->app->singleton(EnterpriseFinancialIntegrityService::class);
        $this->app->singleton(EnterpriseEthicsSocialLicenseService::class);
        $this->app->singleton(EnterpriseFutureReadinessService::class);
        $this->app->singleton(EnterpriseLearningFlywheelService::class);
        $this->app->singleton(EnterpriseDigitalTrustService::class);
    }

    public function boot(): void
    {
        $this->loadMigrationsFrom(__DIR__.'/database/migrations');

        if (file_exists(__DIR__.'/routes/web.php')) {
            $this->loadRoutesFrom(__DIR__.'/routes/web.php');
        }

        if (is_dir(__DIR__.'/resources/views/integration')) {
            $this->loadViewsFrom(__DIR__.'/resources/views/integration', 'integration');
        }

        if ($this->app->runningInConsole()) {
            $this->commands([
                AuditIntegrationCommand::class,
                SecurityAuditCommand::class,
                DrAuditCommand::class,
            ]);
        }

        $this->registerMenu();
    }

    protected function registerMenu(): void
    {
        if (! $this->app->bound(MenuRegistry::class)) {
            return;
        }

        $this->app->make(MenuRegistry::class)->addItem(
            label: 'Integrasi API & EDI',
            route: 'integration.index',
            icon: 'code-bracket',
            roles: ['admin', 'auditor'],
            order: 69,
            group: 'Sistem & Keamanan',
            activePattern: 'integration*',
        );
    }
}
