<?php

declare(strict_types=1);

namespace Modules\Logistics\database\seeders;

use Illuminate\Database\Seeder;
use Modules\Logistics\Domain\Enums\LocationType;
use Modules\Logistics\Domain\Enums\TransportMode;
use Modules\Logistics\Domain\Models\Lane;
use Modules\Logistics\Domain\Models\Location;

class LogisticsNetworkSeeder extends Seeder
{
    public function run(): void
    {
        // 1. Locations
        $locations = [
            // Pelabuhan Laut (Seaports) with UN/LOCODE
            [
                'code' => 'PORT-IDBDJ',
                'name' => 'Pelabuhan Trisakti Banjarmasin',
                'type' => LocationType::SEAPORT,
                'unlocode' => 'IDBDJ',
                'iata' => null,
                'city' => 'Banjarmasin',
                'province' => 'Kalimantan Selatan',
                'country' => 'ID',
                'lat_e6' => -3327500,
                'lng_e6' => 114568300,
                'timezone' => 'Asia/Makassar',
                'min_connection_minutes' => 180,
            ],
            [
                'code' => 'PORT-IDTPP',
                'name' => 'Pelabuhan Tanjung Priok Jakarta',
                'type' => LocationType::SEAPORT,
                'unlocode' => 'IDTPP',
                'iata' => null,
                'city' => 'Jakarta Utara',
                'province' => 'DKI Jakarta',
                'country' => 'ID',
                'lat_e6' => -6103300,
                'lng_e6' => 106883300,
                'timezone' => 'Asia/Jakarta',
                'min_connection_minutes' => 240,
            ],
            [
                'code' => 'PORT-IDSUB',
                'name' => 'Pelabuhan Tanjung Perak Surabaya',
                'type' => LocationType::SEAPORT,
                'unlocode' => 'IDSUB',
                'iata' => null,
                'city' => 'Surabaya',
                'province' => 'Jawa Timur',
                'country' => 'ID',
                'lat_e6' => -7198300,
                'lng_e6' => 112731700,
                'timezone' => 'Asia/Jakarta',
                'min_connection_minutes' => 210,
            ],
            [
                'code' => 'PORT-IDBLW',
                'name' => 'Pelabuhan Belawan Medan',
                'type' => LocationType::SEAPORT,
                'unlocode' => 'IDBLW',
                'iata' => null,
                'city' => 'Medan',
                'province' => 'Sumatera Utara',
                'country' => 'ID',
                'lat_e6' => 3783300,
                'lng_e6' => 98683300,
                'timezone' => 'Asia/Jakarta',
                'min_connection_minutes' => 240,
            ],
            [
                'code' => 'PORT-IDMAK',
                'name' => 'Pelabuhan Soekarno-Hatta Makassar',
                'type' => LocationType::SEAPORT,
                'unlocode' => 'IDMAK',
                'iata' => null,
                'city' => 'Makassar',
                'province' => 'Sulawesi Selatan',
                'country' => 'ID',
                'lat_e6' => -5116700,
                'lng_e6' => 119416700,
                'timezone' => 'Asia/Makassar',
                'min_connection_minutes' => 210,
            ],
            [
                'code' => 'PORT-SGSIN',
                'name' => 'Port of Singapore',
                'type' => LocationType::SEAPORT,
                'unlocode' => 'SGSIN',
                'iata' => null,
                'city' => 'Singapore',
                'province' => 'Singapore',
                'country' => 'SG',
                'lat_e6' => 1283300,
                'lng_e6' => 103850000,
                'timezone' => 'Asia/Singapore',
                'min_connection_minutes' => 300,
            ],
            [
                'code' => 'PORT-CNSHA',
                'name' => 'Port of Shanghai',
                'type' => LocationType::SEAPORT,
                'unlocode' => 'CNSHA',
                'iata' => null,
                'city' => 'Shanghai',
                'province' => 'Shanghai',
                'country' => 'CN',
                'lat_e6' => 31230400,
                'lng_e6' => 121473700,
                'timezone' => 'Asia/Shanghai',
                'min_connection_minutes' => 360,
            ],

            // Bandar Udara (Airports) with IATA
            [
                'code' => 'AIRP-BDJ',
                'name' => 'Bandara Internasional Syamsudin Noor',
                'type' => LocationType::AIRPORT,
                'unlocode' => null,
                'iata' => 'BDJ',
                'city' => 'Banjarbaru',
                'province' => 'Kalimantan Selatan',
                'country' => 'ID',
                'lat_e6' => -3441700,
                'lng_e6' => 114757500,
                'timezone' => 'Asia/Makassar',
                'min_connection_minutes' => 90,
            ],
            [
                'code' => 'AIRP-CGK',
                'name' => 'Bandara Internasional Soekarno-Hatta',
                'type' => LocationType::AIRPORT,
                'unlocode' => null,
                'iata' => 'CGK',
                'city' => 'Tangerang',
                'province' => 'Banten',
                'country' => 'ID',
                'lat_e6' => -6125600,
                'lng_e6' => 106655800,
                'timezone' => 'Asia/Jakarta',
                'min_connection_minutes' => 120,
            ],
            [
                'code' => 'AIRP-SUB',
                'name' => 'Bandara Internasional Juanda',
                'type' => LocationType::AIRPORT,
                'unlocode' => null,
                'iata' => 'SUB',
                'city' => 'Sidoarjo',
                'province' => 'Jawa Timur',
                'country' => 'ID',
                'lat_e6' => -7379700,
                'lng_e6' => 112787500,
                'timezone' => 'Asia/Jakarta',
                'min_connection_minutes' => 105,
            ],
            [
                'code' => 'AIRP-UPG',
                'name' => 'Bandara Internasional Sultan Hasanuddin',
                'type' => LocationType::AIRPORT,
                'unlocode' => null,
                'iata' => 'UPG',
                'city' => 'Maros',
                'province' => 'Sulawesi Selatan',
                'country' => 'ID',
                'lat_e6' => -5061700,
                'lng_e6' => 119554200,
                'timezone' => 'Asia/Makassar',
                'min_connection_minutes' => 105,
            ],
            [
                'code' => 'AIRP-BPN',
                'name' => 'Bandara Internasional Sultan Aji Muhammad Sulaiman Sepinggan',
                'type' => LocationType::AIRPORT,
                'unlocode' => null,
                'iata' => 'BPN',
                'city' => 'Balikpapan',
                'province' => 'Kalimantan Timur',
                'country' => 'ID',
                'lat_e6' => -1268300,
                'lng_e6' => 116894400,
                'timezone' => 'Asia/Makassar',
                'min_connection_minutes' => 90,
            ],
            [
                'code' => 'AIRP-KNO',
                'name' => 'Bandara Internasional Kualanamu',
                'type' => LocationType::AIRPORT,
                'unlocode' => null,
                'iata' => 'KNO',
                'city' => 'Deli Serdang',
                'province' => 'Sumatera Utara',
                'country' => 'ID',
                'lat_e6' => 3642200,
                'lng_e6' => 98885300,
                'timezone' => 'Asia/Jakarta',
                'min_connection_minutes' => 120,
            ],
            [
                'code' => 'AIRP-SIN',
                'name' => 'Singapore Changi Airport',
                'type' => LocationType::AIRPORT,
                'unlocode' => null,
                'iata' => 'SIN',
                'city' => 'Singapore',
                'province' => 'Singapore',
                'country' => 'SG',
                'lat_e6' => 1364400,
                'lng_e6' => 103991500,
                'timezone' => 'Asia/Singapore',
                'min_connection_minutes' => 150,
            ],
            [
                'code' => 'AIRP-PVG',
                'name' => 'Shanghai Pudong International Airport',
                'type' => LocationType::AIRPORT,
                'unlocode' => null,
                'iata' => 'PVG',
                'city' => 'Shanghai',
                'province' => 'Shanghai',
                'country' => 'CN',
                'lat_e6' => 31144300,
                'lng_e6' => 121808300,
                'timezone' => 'Asia/Shanghai',
                'min_connection_minutes' => 180,
            ],

            // Hub Darat (Land Hubs)
            [
                'code' => 'HUB-BDJ',
                'name' => 'Hub Logistik Banjarmasin Basirih (Central)',
                'type' => LocationType::HUB,
                'unlocode' => null,
                'iata' => null,
                'city' => 'Banjarmasin',
                'province' => 'Kalimantan Selatan',
                'country' => 'ID',
                'lat_e6' => -3342200,
                'lng_e6' => 114580600,
                'timezone' => 'Asia/Makassar',
                'min_connection_minutes' => 45,
            ],
            [
                'code' => 'HUB-BJB',
                'name' => 'Hub Logistik Banjarbaru',
                'type' => LocationType::HUB,
                'unlocode' => null,
                'iata' => null,
                'city' => 'Banjarbaru',
                'province' => 'Kalimantan Selatan',
                'country' => 'ID',
                'lat_e6' => -3440000,
                'lng_e6' => 114830000,
                'timezone' => 'Asia/Makassar',
                'min_connection_minutes' => 45,
            ],
            [
                'code' => 'HUB-MTP',
                'name' => 'Hub Logistik Martapura',
                'type' => LocationType::HUB,
                'unlocode' => null,
                'iata' => null,
                'city' => 'Martapura',
                'province' => 'Kalimantan Selatan',
                'country' => 'ID',
                'lat_e6' => -3415000,
                'lng_e6' => 114860000,
                'timezone' => 'Asia/Makassar',
                'min_connection_minutes' => 45,
            ],
            [
                'code' => 'HUB-PKY',
                'name' => 'Hub Logistik Palangkaraya',
                'type' => LocationType::HUB,
                'unlocode' => null,
                'iata' => null,
                'city' => 'Palangkaraya',
                'province' => 'Kalimantan Tengah',
                'country' => 'ID',
                'lat_e6' => -2210000,
                'lng_e6' => 113920000,
                'timezone' => 'Asia/Jakarta',
                'min_connection_minutes' => 60,
            ],
            [
                'code' => 'HUB-BPN',
                'name' => 'Hub Logistik Balikpapan Kariangau',
                'type' => LocationType::HUB,
                'unlocode' => null,
                'iata' => null,
                'city' => 'Balikpapan',
                'province' => 'Kalimantan Timur',
                'country' => 'ID',
                'lat_e6' => -1240000,
                'lng_e6' => 116860000,
                'timezone' => 'Asia/Makassar',
                'min_connection_minutes' => 60,
            ],
            [
                'code' => 'HUB-SMD',
                'name' => 'Hub Logistik Samarinda Palaran',
                'type' => LocationType::HUB,
                'unlocode' => null,
                'iata' => null,
                'city' => 'Samarinda',
                'province' => 'Kalimantan Timur',
                'country' => 'ID',
                'lat_e6' => -500000,
                'lng_e6' => 117150000,
                'timezone' => 'Asia/Makassar',
                'min_connection_minutes' => 60,
            ],

            // CFS & Depot Kontainer
            [
                'code' => 'CFS-BDJ',
                'name' => 'Container Freight Station (CFS) Trisakti',
                'type' => LocationType::CFS,
                'unlocode' => null,
                'iata' => null,
                'city' => 'Banjarmasin',
                'province' => 'Kalimantan Selatan',
                'country' => 'ID',
                'lat_e6' => -3329000,
                'lng_e6' => 114569500,
                'timezone' => 'Asia/Makassar',
                'min_connection_minutes' => 60,
            ],
            [
                'code' => 'DEP-BDJ',
                'name' => 'Depot Kontainer Sari Ranah Basirih',
                'type' => LocationType::DEPOT,
                'unlocode' => null,
                'iata' => null,
                'city' => 'Banjarmasin',
                'province' => 'Kalimantan Selatan',
                'country' => 'ID',
                'lat_e6' => -3345000,
                'lng_e6' => 114585000,
                'timezone' => 'Asia/Makassar',
                'min_connection_minutes' => 60,
            ],
            [
                'code' => 'DEP-SUB',
                'name' => 'Depot Kontainer Kalimas Tanjung Perak',
                'type' => LocationType::DEPOT,
                'unlocode' => null,
                'iata' => null,
                'city' => 'Surabaya',
                'province' => 'Jawa Timur',
                'country' => 'ID',
                'lat_e6' => -7205000,
                'lng_e6' => 112735000,
                'timezone' => 'Asia/Jakarta',
                'min_connection_minutes' => 60,
            ],
            [
                'code' => 'DEP-TPP',
                'name' => 'Depot Kontainer Cakung Cikarang',
                'type' => LocationType::DEPOT,
                'unlocode' => null,
                'iata' => null,
                'city' => 'Jakarta Timur',
                'province' => 'DKI Jakarta',
                'country' => 'ID',
                'lat_e6' => -6170000,
                'lng_e6' => 106940000,
                'timezone' => 'Asia/Jakarta',
                'min_connection_minutes' => 60,
            ],
        ];

        $locationModels = [];
        foreach ($locations as $loc) {
            $locationModels[$loc['code']] = Location::updateOrCreate(
                ['code' => $loc['code']],
                $loc
            );
        }

        // 2. Lanes
        $lanes = [
            // Road Lanes (Darat)
            ['HUB-BDJ', 'HUB-BJB', TransportMode::ROAD, 35_000, 60],
            ['HUB-BJB', 'HUB-BDJ', TransportMode::ROAD, 35_000, 60],
            ['HUB-BJB', 'HUB-MTP', TransportMode::ROAD, 15_000, 30],
            ['HUB-MTP', 'HUB-BJB', TransportMode::ROAD, 15_000, 30],
            ['HUB-BDJ', 'HUB-PKY', TransportMode::ROAD, 190_000, 300],
            ['HUB-PKY', 'HUB-BDJ', TransportMode::ROAD, 190_000, 300],
            ['HUB-BDJ', 'HUB-BPN', TransportMode::ROAD, 480_000, 720],
            ['HUB-BPN', 'HUB-BDJ', TransportMode::ROAD, 480_000, 720],
            ['HUB-BPN', 'HUB-SMD', TransportMode::ROAD, 115_000, 150],
            ['HUB-SMD', 'HUB-BPN', TransportMode::ROAD, 115_000, 150],
            ['HUB-BDJ', 'PORT-IDBDJ', TransportMode::ROAD, 10_000, 30],
            ['PORT-IDBDJ', 'HUB-BDJ', TransportMode::ROAD, 10_000, 30],
            ['HUB-BDJ', 'AIRP-BDJ', TransportMode::ROAD, 25_000, 45],
            ['AIRP-BDJ', 'HUB-BDJ', TransportMode::ROAD, 25_000, 45],
            ['PORT-IDBDJ', 'CFS-BDJ', TransportMode::ROAD, 2_000, 15],
            ['CFS-BDJ', 'PORT-IDBDJ', TransportMode::ROAD, 2_000, 15],
            ['PORT-IDBDJ', 'DEP-BDJ', TransportMode::ROAD, 5_000, 20],
            ['DEP-BDJ', 'PORT-IDBDJ', TransportMode::ROAD, 5_000, 20],
            ['PORT-IDSUB', 'DEP-SUB', TransportMode::ROAD, 6_000, 25],
            ['DEP-SUB', 'PORT-IDSUB', TransportMode::ROAD, 6_000, 25],
            ['PORT-IDTPP', 'DEP-TPP', TransportMode::ROAD, 15_000, 45],
            ['DEP-TPP', 'PORT-IDTPP', TransportMode::ROAD, 15_000, 45],

            // Sea Lanes (Laut)
            ['PORT-IDBDJ', 'PORT-IDSUB', TransportMode::SEA, 510_000, 1_440], // ~24h
            ['PORT-IDSUB', 'PORT-IDBDJ', TransportMode::SEA, 510_000, 1_440],
            ['PORT-IDBDJ', 'PORT-IDTPP', TransportMode::SEA, 960_000, 2_880], // ~48h
            ['PORT-IDTPP', 'PORT-IDBDJ', TransportMode::SEA, 960_000, 2_880],
            ['PORT-IDBDJ', 'PORT-IDMAK', TransportMode::SEA, 540_000, 1_560], // ~26h
            ['PORT-IDMAK', 'PORT-IDBDJ', TransportMode::SEA, 540_000, 1_560],
            ['PORT-IDSUB', 'PORT-IDTPP', TransportMode::SEA, 680_000, 1_920], // ~32h
            ['PORT-IDTPP', 'PORT-IDSUB', TransportMode::SEA, 680_000, 1_920],
            ['PORT-IDTPP', 'PORT-IDBLW', TransportMode::SEA, 1_450_000, 4_320], // ~72h
            ['PORT-IDBLW', 'PORT-IDTPP', TransportMode::SEA, 1_450_000, 4_320],
            ['PORT-IDTPP', 'PORT-SGSIN', TransportMode::SEA, 1_000_000, 2_880], // ~48h
            ['PORT-SGSIN', 'PORT-IDTPP', TransportMode::SEA, 1_000_000, 2_880],
            ['PORT-SGSIN', 'PORT-CNSHA', TransportMode::SEA, 4_200_000, 10_080], // ~7 days
            ['PORT-CNSHA', 'PORT-SGSIN', TransportMode::SEA, 4_200_000, 10_080],

            // Air Lanes (Udara)
            ['AIRP-BDJ', 'AIRP-CGK', TransportMode::AIR, 950_000, 80],
            ['AIRP-CGK', 'AIRP-BDJ', TransportMode::AIR, 950_000, 80],
            ['AIRP-BDJ', 'AIRP-SUB', TransportMode::AIR, 500_000, 60],
            ['AIRP-SUB', 'AIRP-BDJ', TransportMode::AIR, 500_000, 60],
            ['AIRP-BDJ', 'AIRP-UPG', TransportMode::AIR, 600_000, 75],
            ['AIRP-UPG', 'AIRP-BDJ', TransportMode::AIR, 600_000, 75],
            ['AIRP-BDJ', 'AIRP-BPN', TransportMode::AIR, 350_000, 45],
            ['AIRP-BPN', 'AIRP-BDJ', TransportMode::AIR, 350_000, 45],
            ['AIRP-CGK', 'AIRP-SIN', TransportMode::AIR, 900_000, 100],
            ['AIRP-SIN', 'AIRP-CGK', TransportMode::AIR, 900_000, 100],
            ['AIRP-SIN', 'AIRP-PVG', TransportMode::AIR, 3_800_000, 300],
            ['AIRP-PVG', 'AIRP-SIN', TransportMode::AIR, 3_800_000, 300],
            ['AIRP-CGK', 'AIRP-KNO', TransportMode::AIR, 1_400_000, 130],
            ['AIRP-KNO', 'AIRP-CGK', TransportMode::AIR, 1_400_000, 130],
        ];

        foreach ($lanes as [$origCode, $destCode, $mode, $dist, $transit]) {
            $orig = $locationModels[$origCode] ?? Location::where('code', $origCode)->first();
            $dest = $locationModels[$destCode] ?? Location::where('code', $destCode)->first();

            if ($orig && $dest) {
                Lane::updateOrCreate(
                    [
                        'origin_id' => $orig->id,
                        'destination_id' => $dest->id,
                        'mode' => $mode,
                    ],
                    [
                        'distance_m' => $dist,
                        'standard_transit_minutes' => $transit,
                        'is_active' => true,
                    ]
                );
            }
        }
    }
}
